### ISSUE TITLE
LDTK Tile stacking

### ISSUE THREAD

**Issue by boyswan** [StarArawn/bevy_ecs_tilemap#105]
Stacked tiles within a single layer are only rendering the top tile. Is the tile stacking feature from LDTK intended to work?

**Comment by StarArawn** [comment]
Please see:
https://github.com/StarArawn/bevy_ecs_tilemap/issues/84

**Comment by StarArawn** [comment]
> After doing some digging, I think that this issue is less to do with LDTK itself and more down to the fact that bevy_ecs doesn't render multiple tiles (if they exist) within the same tile coordinates. Is this the case?

Yes, currently you need separate layers.

**Comment by StarArawn** [comment]
I don't see a reason to keep this open anymore so I'm close the issue. Please make a new issue if you think its necessary!
