### ISSUE TITLE
Feature request: Allow texture indexing for TextureAtlases built through TextureAtlasBuilder

### ISSUE THREAD

**Issue by Seldom-SE** [StarArawn/bevy_ecs_tilemap#112]
Unless I am mistaken, when using a `TextureAtlas` built with a `TextureAtlasBuilder` as a tilemap's texture atlas, the `Tile`s' `texture_index`es do not map to the `TextureAtlasSprite`s' `index`es of the same texture. This means that attempting to use indexes retrieved through `texture_atlas.get_texture_index` in a `Tile` results in unpredictable textures being displayed. And since the order of the sprites in a generated `TextureAtlas` cannot be known until runtime, using `TextureAtlasBuilder` with `bevy_ecs_tilemap` is infeasible. I wrote a simple example to demonstrate this issue: https://github.com/Seldom-SE/bevy_ecs_tilemap-TextureAtlas-demo.

Perhaps a method may be added to `LayerBuilder` to provide a `Handle<TextureAtlas>`, so the `TextureAtlas`'s indexing may be used instead. Unfortunately, this could conflict with the `material_handle` passed into `map_query.build_layer`.

I am willing to contribute work on this, if it is desired. Thanks!

**Comment by MrGVSV** [comment]
I actually just made something in my [fork](https://github.com/MrGVSV/bevy_ecs_tilemap/pull/1) of this repo that might help. It adds a `TileAtlasBuilder` which can be used to generate a `TextureAtlas` that maintains order of insertion, so it should work with the current system.

If @StarArawn wants something like this merged, I can open a PR. Otherwise, feel free to just copy the `TileAtlasBuilder` code!

**Comment by Seldom-SE** [comment]
This looks like it could help, thanks! I might use this once I inevitably refactor my level code again.

**Comment by MrGVSV** [comment]
> This looks like it could help, thanks! I might use this once I inevitably refactor my level code again.

@Seldom-SE I actually just published this in its own crate so it can be used in a more general sense (not just for `bevy_ecs_tilemap`). Feel free to check it out [here](https://crates.io/crates/bevy_tile_atlas)!

**Comment by Seldom-SE** [comment]
This is very helpful, thanks! I'm partway transitioned to using it now.

I'll leave this issue open, though, in case they want to come to their own solution.

**Comment by StarArawn** [comment]
The plan currently is to switch to a texture array. When I do that I can leverage mipmaps(when bevy comes up with a solution for these) and texture filtering. Things that you cannot easily use with an atlas.

**Comment by StarArawn** [comment]
I'm going to close this as there is now a `TileAtlasBuilder`! 🎉

**Comment by MrGVSV** [comment]
> I'm going to close this as there is now a `TileAtlasBuilder`! 🎉 

Wow I just realized that it was sneaked in via the rebase in #120. Sorry if you didn't actually want it, had no idea it did that 😅

**Comment by StarArawn** [comment]
> > I'm going to close this as there is now a `TileAtlasBuilder`! 🎉
> 
> Wow I just realized that it was sneaked in via the rebase in #120. Sorry if you didn't actually want it, had no idea it did that 😅

It's all good I think its still useful as I'm leaning towards making the texture array stuff all internal and users just use atlases with the API.
