### ISSUE TITLE
GPUAnimated Not Working

### ISSUE THREAD

**Issue by MrGVSV** [StarArawn/bevy_ecs_tilemap#116]
I have a testing tileset:
![tileset](https://user-images.githubusercontent.com/49806985/142281583-0f0defbe-3a3d-4863-b1e0-b13bc9efba46.png)

However, I can't get it to animate over the flowers by writing:
```rust
commands.entity(entity).insert(GPUAnimated::new(3, 5, 0.9));
```

Changing this to run from index 0 or 1 works:
```rust
commands.entity(entity).insert(GPUAnimated::new(0, 5, 0.9));
```

I also added this tileset to the `animation` example (adjusting the tile and texture size appropriately) and faced the same issue. Is this an internal issue or something I'm doing worng?

**Comment by B-Reif** [comment]
I'm experiencing this issue currently on main. It manifests the same way, where running from index 0 or 1 works.
