### ISSUE TITLE
Tile tints

### ISSUE THREAD

**Issue by MrGVSV** [StarArawn/bevy_ecs_tilemap#119]
Is there any way to add a color tint to a specific tile?

For example, if I need to indicate that a tile can't be placed, I might want to give it a red tint. Or green, if it can be placed.

Is this something that this crate supports via a shader? Or is there another way to go about handling this?

**Comment by MrGVSV** [comment]
Oh sweet! Is this going to be a part of the next release?

**Comment by StarArawn** [comment]
> Oh sweet! Is this going to be a part of the next release?
Yep! I'm currently waiting on bevy 0.6 to release the next version of bevy_ecs_tilemap.

**Comment by MrGVSV** [comment]
Sounds good. Looking forward to it!
