### ISSUE TITLE
Chunk becomes invisible when zooming camera

### ISSUE THREAD

**Issue by tdbgamer** [StarArawn/bevy_ecs_tilemap#124]
https://user-images.githubusercontent.com/3655689/145882710-523e5bbe-7cb8-4afa-b616-8839606ee52f.mp4

**Comment by StarArawn** [comment]
Yeah, I have a Todo to fix this as the chunk culling is completely broken at the moment.. In the new renderer I turned off the culling.

**Comment by StarArawn** [comment]
@tdbgamer Can you test this again on the `new-renderer` branch? Not sure how much work that is for you, but it should be fixed now.

**Comment by StarArawn** [comment]
Closing this as I'm fairly certain this issue is fixed..
