### ISSUE TITLE
layer_id and map_id API improvements.

### ISSUE THREAD

**Issue by turboMaCk** [StarArawn/bevy_ecs_tilemap#136]
One thing that confused a hell out of me were seemingly magic numbers in public API. Only after reading the source I understood how these are handled.  I think it would be a good idea to clean this API to make it easier to understand and use correctly.

From my understanding `layer_id` sort of has 2 functions at the moment:

- identifier of layer
- translation.z (z_index)

There also seems to be bug related to how layer_id is currently handled see: https://github.com/StarArawn/bevy_ecs_tilemap/issues/134. For this issue I will be ignoring the translation part.

example code snippet that could be found in many examples and likely in any sort of use-case:

```rust
// initialize map
let map_entity = commands.spawn().id();
let map_id = 0u16;
let mut map = Map::new(map_id, map_entity);

// configure layer
let layer_settings = LayerSettings::new(
    MapSize(2, 2),
    ChunkSize(8, 8),
    TileSize(16.0, 16.0),
    TextureSize(96.0, 16.0),
);

// use one of the ways to set id to the layer.... pick your preferred way...

// set layer_id using public accessor on struct
layer_settings.layer_id = 1u16;
// set layer_id using setter api of settings struct
layer_settings.set_layer_id(1u16);

// use one of the ways to set map id to the layer.... pick your preferred way...

// set layer_id using public accessor on struct
layer_settings.map_id = map_id;
// set layer_id using setter api of settings struct
layer_settings.set_map_id(map_id);

// initialize layer builder repeating layer_id and map_id (repeating what we did above)
// you can clearly see that we pass these values twice
//    - as part of layer_settings
//    - as own argumnet
let (mut layer, layer_entity) =
        LayerBuilder::new(&mut commands, layer_settings, layer_settings.map_id, layer_settings.layer_id);
        
//  use builder in some way ...

// add layer to map...  repeating map_id one more time.
map.add_layer(&mut commands, layer_settings.map_id, layer_entity);
```

I think this can be more sensible. The clearest part is `LayerBuilder::new` which esentially takes both arguments twice (as part of `LayerSettings` struct and own argument. It actually just calls the setters on `LayerSettings` before using them: https://github.com/StarArawn/bevy_ecs_tilemap/blob/a19c563f5bc44a21b20825a4f38c64c872a0eea0/src/layer_builder.rs#L48-L49 another method with doing the similar thing is `new_batch` https://github.com/StarArawn/bevy_ecs_tilemap/blob/a19c563f5bc44a21b20825a4f38c64c872a0eea0/src/layer_builder.rs#L79-L80

For this case I think `layer_id` and  `map_id` either should be part of `LayerSettings` and then never be passed as own argument or they shouldn't be part of `LayerSettings` in first place. I think later might be more ergonomic in cases where user wants to easily reuse same settings for multiple layers. Also note that almost all examples that use `layer_id` other than default `0u16` seems to set this value twice.

Even `map_id` in `add_layer` would be IMO better to avoid. Especially since `Map` struct has this on `self` https://github.com/StarArawn/bevy_ecs_tilemap/blob/a19c563f5bc44a21b20825a4f38c64c872a0eea0/src/map.rs#L10.

## Proposed API

This is how I would like to be able to write the code above:

```rust
// initialize map
let mut map = Map::new(&mut commands, 0u16);

// configure layer
let layer_settings = LayerSettings::new(
    MapSize(2, 2),
    ChunkSize(8, 8),
    TileSize(16.0, 16.0),
    TextureSize(96.0, 16.0),
);

// initialize layer builder. layer_id is set at this point.
// also notice no tuple - this would be new struct that holds entity & layer_id internally
let layer_builder =
        LayerBuilder::new(&mut commands, 1u16, layer_settings);
        
//  use builder in some way ...

// add layer to map... map_id is set here
map.add_layer(&mut commands, layer_builder);
```

I did not check how simple it would be to avoid setting map_id in any way before `add_layer` call but I believe at least `layer_id` part will be simple to implement.

**Comment by alice-i-cecile** [comment]
I like this! The example code is much clearer. Given that we already have access to `&mut commands` in `map.add_layer`, why not just pass in the `LayerSettings` directly?

**Comment by turboMaCk** [comment]
In my own code I have few small wrappers that do this. Anyway `LayerSettings` is not really enough because `add_layer` also needs an entity which is returned from `LayerBuilder::new()`. Also what is missing in my example is part of code that actually uses builder to fill it with tiles. Anyway this is the code I use in my project. It simplifies things even further but it also does maybe a bit too much to be useful generally:

implementation:

<details>

```rust
struct MapTileSettings<'a> {
    src: &'a str,
    cols: usize,
    rows: usize,
    z_index: u16,
}

impl<'a> MapTileSettings<'a> {
    fn load(
        &self,
        cmds: &mut Commands,
        map: &mut Map,
        asset_server: &AssetServer,
        materials: &mut Assets<ColorMaterial>,
    ) -> MapLayer {
        let tiles = asset_server.load(self.src);
        let atlas =
            TextureAtlas::from_grid(tiles, Vec2::new(TILE_SIZE, TILE_SIZE), self.cols, self.rows);
        let atlas_material = materials.add(ColorMaterial::texture(atlas.texture));

        let mut layer_settings = LayerSettings::new(
            UVec2::new(MAP_SIZE, MAP_SIZE),
            UVec2::new(CHUNK_SIZE, CHUNK_SIZE),
            Vec2::new(TILE_SIZE, TILE_SIZE),
            Vec2::new(atlas.size.x, atlas.size.y),
        );
        layer_settings.set_layer_id(self.z_index);

        let (builder, entity) = LayerBuilder::new(cmds, layer_settings.clone(), 0u16, self.z_index);
        map.add_layer(cmds, self.z_index, entity);

        MapLayer {
            material: atlas_material,
            layer_settings,
            builder,
        }
    }

    fn get_index(&self, x: u16, y: u16) -> u16 {
        x + self.cols as u16 * y
    }
}

struct MapLayer {
    material: Handle<ColorMaterial>,
    layer_settings: LayerSettings,
    builder: LayerBuilder<TileBundle>,
}

impl MapLayer {
    fn set_tile(&mut self, tile_pos: UVec2, tile: TileBundle) -> Result<(), MapTileError> {
        self.builder.set_tile(tile_pos, tile)
    }
}
```

</details>

usage:

```rust
    let mut floor_layer = FLOOR_TILES.load(&mut cmds, &mut map, &asset_server, &mut materials);
    let mut wall_layer = WALL_TILES.load(&mut cmds, &mut map, &asset_server, &mut materials);
    let mut top_layer = TOP_TILES.load(&mut cmds, &mut map, &asset_server, &mut materials);
    
    /// set tile in some layer based on data...
    
     wall_layer.set_tile(
        loc, // coords
        TileBundle {
            tile: Tile {
                texture_index: FLOOR_TILES.get_index(2, 4);
                ..Default::default()
            },
            ..Default::default()
        },
    )
```

There I do quite a lof of stuff behind simple `load` which I use to define tile layers but I'm also making quite a few assumptions which I might not be appropriate to make in library. Anyway I simply do these things when initializing consts like:

```rust
const FLOOR_TILES: MapTileSettings<'static> = MapTileSettings {
    src: "textures/dungeon/floors.png",
    cols: 3,
    rows: 4,
    z_index: 0,
};
```

this does all the texture and material handling as well as creates layer and so on.

Anyway to support various use-cases I think it still makes sense to have settings decoupled from builder and use api:

```
declare Settings -> initialize builder -> use builder -> insert builder to map.
```

preferably I think it would nice if last step also forced move of the whole builder - That would add type level grantee it can't be used after it's inserted to map.

**Comment by turboMaCk** [comment]
regarding feasibility I tried to do 1st step - removing `map_id` and `layer_id` from `LayerSettings` struct. While doing so I also fixed several bugs in examples which were caused by confusion around this API (setting layer_id to some value but then overwriting it to 0 when initializing builder)

https://github.com/turboMaCk/bevy_ecs_tilemap/commit/60670e4de077b9f043d771c6b6ef15320307913d

**Anyway I based my branch off v0.4.0 and not master since that's what I'm using.**

**Comment by StarArawn** [comment]
One problem with the proposed API is the fact that `map_id` is required to do a reverse lookup of a tile. Look at code referencing `TileParent`. I have implemented some of the changes here:
https://github.com/StarArawn/bevy_ecs_tilemap/pull/139
