### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by rparrett** [StarArawn/bevy_ecs_tilemap#143]
With the switch to array textures, we lost wasm support.

There seem to be several separate issues:

1. When the number of tiles in a tileset is either 1 or divisible by 6, the texture is treated as a cubemap and tiles show up at all.

https://github.com/gfx-rs/wgpu/issues/2161

2. Some other mysterious issue, which results in tiles showing up black

> StarToaster — Today at 12:23 PM
> There might be wgpu bug with copy_texture_to_texture and arrays on webgl

I was unable to dig up a relevant issue for that one in the wgpu tracker

3. We are limited to 256 tiles in a tileset due to texture dimension limits in wgpu.

This may have been fixed/mitigated by https://github.com/bevyengine/bevy/pull/3452

**Comment by StarArawn** [comment]
Fixed by: #144
