### ISSUE TITLE
Possible rendering bug?

### ISSUE THREAD

**Issue by sizeak** [StarArawn/bevy_ecs_tilemap#149]
Hi,

I just updated to 0.5.0 and made the necessary changes to migrate, primarily adjusting to the `layer_id` no longer being public and adding the texture filter helper system `set_texture_filters_to_nearest` to get things working again. While it is rendering the tilemap again, I have weird behaviour where some tiles seem to disappear when I translate the camera, previously everything rendered perfectly. I thought it might be related to the chunk size, but I've tried various things to no avail. 

Here is a video example of what I'm seeing, the line shouldn't suddenly appear. Any ideas?

https://user-images.githubusercontent.com/301084/150021113-5149d6b5-1ef9-480f-a0e8-a90558fc9122.mp4

**Comment by StarArawn** [comment]
This looks like an issue with how isometric maps are culled. Can you try turning off culling? You can use the following option to do that:
`layer_settings.cull = false;`

**Comment by sizeak** [comment]
That doesn't seem to have helped unfortunately.

**Comment by sizeak** [comment]
If it's at all useful, I've configured my layer settings like:
```
fn build_map_layer_settings(total_width: u32, total_height: u32, chunk_size: u32) -> LayerSettings {
    let map_height = total_height / chunk_size;
    let map_width = total_width / chunk_size;

    let mut layer_settings = LayerSettings::new(
        MapSize(map_width, map_height),
        ChunkSize(chunk_size, chunk_size),
        TileSize(128.0, 160.0),
        TextureSize(640.0, 160.0),
    );
    layer_settings.grid_size = Vec2::new(128.0, 64.0);
    layer_settings.mesh_type = TilemapMeshType::Isometric(IsoType::Diamond);
    layer_settings.cull = false;
    layer_settings
}
```

I've reproduced this with various values passed into this function, but the video above was made with
```
let total_width = 64;
let total_height = 64;
let chunk_size = 16;
```

I'm building the map in a loop like this (cut down for brevity):
```
for z in 0..depth {
        let (mut layer_builder, layer_entity) =
            LayerBuilder::new(commands, layer_settings, map_id, z as u16);

        for x in 0..width {
            for y in 0..height {

                    layer_builder
                        .set_tile(
                            TilePos(x, y),
                            // omitted code
                        )
            }
        }

        map_query.build_layer(&mut commands, layer_builder, texture_handle.clone());
        map.add_layer(&mut commands, z as u16, layer_entity);
    }
```

**Comment by StarArawn** [comment]
@sizeak
Hi! I think I figured out part of the issue here. Please see this branch: `iso-fixes` for a possible fix..

**Comment by sizeak** [comment]
Hi, Thanks for looking into this for me so quickly!

I switched to that branch in `Cargo.toml`, that's the only change I've made since the previous videos I posted. The world is no longer rendering as a diamond and the previous issues also persists. Is there anything I can do to help you track it down?

https://user-images.githubusercontent.com/301084/150651916-eaf47a92-04a8-4fed-a1b6-72d639ed44fe.mp4

**Comment by StarArawn** [comment]
@sizeak Sorry this took a bit of time, but I managed to track down the issues and I have a PR here that should fix ISO issues:
https://github.com/StarArawn/bevy_ecs_tilemap/pull/154
Please let me know if this solves your issue! :)

**Comment by sizeak** [comment]
Hey, no rush, I appreciate you taking the time to look into it. Do I need to make any other changes to my code other than building against the PR branch? I updated `Cargo.toml` with 
```
[dependencies]
bevy = { version = "0.6.0", features = ["dynamic"] } # Don't release with dynamic linking enabled.
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap.git", branch = "new-storage" }
```

and re-built but can still trigger the issue. I scanned the PR and the only relevant change I saw that I might need to make was switching to `TilemapMeshType::Isometric(IsoType::Diamond3d);`, but then only a single tile from each layer is rendered, so it's quite possible I'm doing something stupid.

Let me know if I can provide anything to help track it down.

**Comment by StarArawn** [comment]
@sizeak There is one additional change make sure you change your map size and chunk size. Because of how bevy orders z indices I have to make each y tile in the same chunk. You can split the x axis into chunks but I'm not sure if that's a great idea unless you're map is really big.

**Comment by sizeak** [comment]
:sob: 
![image](https://user-images.githubusercontent.com/301084/152057344-d00e79a1-e0b2-4ffc-afc6-f19288790137.png)

For my sanity I also set the map `x` to `1` like in the PR and it still only renders a single block :sweat_smile: 
```
fn build_map_layer_settings(block_map: &BlockMap, _chunk_size: u32) -> LayerSettings {
    // let map_height = block_map.height / chunk_size;
    // let map_width = block_map.width / chunk_size;

    let mut layer_settings = LayerSettings::new(
        MapSize(1, block_map.height),
        ChunkSize(block_map.width, 1),
        TileSize(128.0, 160.0),
        TextureSize(640.0, 160.0),
    );
    layer_settings.grid_size = Vec2::new(128.0, 64.0);
    layer_settings.mesh_type = TilemapMeshType::Isometric(IsoType::Diamond3d);
    // layer_settings.cull = false;
    layer_settings
}
```

**Comment by StarArawn** [comment]
@sizeak that makes sense for diamond since the very top is a point and only has 1 tile. What does your camera code look like?

**Comment by sizeak** [comment]
Nothing special, just the orthographic bundle from the example, without the scale adjustment. Is this a z-index thing, am I going to need to set near/far to something else :thinking:

**Comment by StarArawn** [comment]
> Nothing special, just the orthographic bundle from the example, without the scale adjustment. Is this a z-index thing, am I going to need to set near/far to something else 🤔

If you are changing the camera's z index even on accident it can cause issues like this sometimes.

**Comment by sizeak** [comment]
Well, I found the other tiles... this might make you laugh
![image](https://user-images.githubusercontent.com/301084/152065865-d2f1b914-6771-4916-ae3d-73f3c1adace0.png)

**Comment by StarArawn** [comment]
It looks like the chunk positions are wrong

**Comment by sizeak** [comment]
Yeah it'll probably be the tile positions, I haven't adjusted them since changing the chunk & map sizes. I think the grid size is correct, at least it was with the old renderer, because the tile are rectangular, they're quite tall. I'll have a play tomorrow, thanks for all the help!

**Comment by sizeak** [comment]
@StarArawn It's me again, sorry! This was driving me a little mad, so I switched to the example and just increased the map & chunk size. I get the same result:
![image](https://user-images.githubusercontent.com/301084/152562080-8fb282e1-0983-415f-8d53-aced73692dc3.png)

```
diff --git a/examples/improved_iso.rs b/examples/improved_iso.rs
index 18fc2c4..3d91616 100644
--- a/examples/improved_iso.rs
+++ b/examples/improved_iso.rs
@@ -17,8 +17,8 @@ fn startup(mut commands: Commands, asset_server: Res<AssetServer>, mut map_query
     // Important for ISO rendering! In order to order tiles correctly we need a chunk per Y layer.
     // This is why the map size is 4 on the y but only 1 for chunk size.
     let mut map_settings = LayerSettings::new(
-        MapSize(1, 4),
-        ChunkSize(4, 1),
+        MapSize(1, 64),
+        ChunkSize(64, 1),
         TileSize(64.0, 64.0),
         TextureSize(384.0, 64.0),
     );
@@ -78,7 +78,7 @@ fn startup(mut commands: Commands, asset_server: Res<AssetServer>, mut map_query
         let mut random = thread_rng();
 
         for _ in 0..4 {
-            let position = TilePos(random.gen_range(0..3), random.gen_range(0..3));
+            let position = TilePos(random.gen_range(0..63), random.gen_range(0..63));
             // Ignore errors for demo sake.
             let _ = layer_builder.set_tile(
                 position,
(END)
```

It seems like a bug, unless there is some really subtle change in the interface I'm missing.

**Comment by StarArawn** [comment]
Yeah this was a bug! I've implemented a fix here:
https://github.com/StarArawn/bevy_ecs_tilemap/pull/155

I should of tested multiple map sizes! 😰

**Comment by sizeak** [comment]
I do things like that all the time, no worries! If you haven't done it yet, might be worth pulling some of the more complex logic into small functions which you can unit test. I totally get if you don't want to though, I find it a chore forcing myself to write tests unless I'm at work :slightly_smiling_face:

**Comment by StarArawn** [comment]
It's difficult to unit test some of this because its more visual than predictable, but once we have well defined standards I could see unit tests being useful.

**Comment by sizeak** [comment]
Great, it seems all sorted now, absolute hero! 

One other thing I've noticed which isn't really to do with this issue (I'll open a new one if needed) is adding multiple layers really tanks performance. It seems to handle 256*256 maps without issue, but add 10 layers and the fps drops to 5 - 10 in release mode. This is my gaming machine too, so it's not exactly lacking in compute or gpu resource. Any ideas?

**Comment by StarArawn** [comment]
@sizeak Yep GPU draw call saturation. :( Because of how bevy's new 2D renderer works we have to split chunks by Y tile for iso. One thing that'll help is proper iso chunk culling I'll try to get that fixed as well. 🤔

**Comment by sizeak** [comment]
Ahh make sense. I'll look forward it, thanks for all the help, I'll close this as fixed now.
