### ISSUE TITLE
`LayerBuilder::for_each_tiles` won't create entities as needed

### ISSUE THREAD

**Issue by BrettWitty** [StarArawn/bevy_ecs_tilemap#163]
I'm attempting to set all tiles of a layer to be `GPUAnimated`. I'm using bevy v0.6.1 and bevy_ecs_tilemap v0.5.0.

I assumed I could use `set_all` or `fill` to set the initial frame, then use `for_each_tiles` to add in the `GPUAnimated` component. However `set_all` and `fill` do not create tile entities prior to layer building. The animation example in the repo uses `get_tile_entity` which *does* create an entity if it doesn't exist, but you need to explicitly loop through all the `TilePos`.

I found this confusing.

**Comment by StarArawn** [comment]
This is no longer an issue since the API has changed.
