### ISSUE TITLE
Is there a way to flip the X Axis?

### ISSUE THREAD

**Issue by ghmendonca** [StarArawn/bevy_ecs_tilemap#167]
So the map always renders the tiles to right and up, but I'm using the `Tiled` software to build my map and in their grid it's right and down, which sucks because the map is wrong when rendered.

So I'm wondering if there is a way to render the tiles to the right and down (flip the x axis)?

**Comment by StarArawn** [comment]
I believe you need to flip the Y axis. There is an example of how to do this here:
https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/examples/tiled/tiled.rs#L203

**Comment by ghmendonca** [comment]
@StarArawn thanks for the answer! Managed to flip the Y axis by iterating my matrix of tiles from bottom to top, since my map is server side, the client only receives the 25x25 map tiles to render whenever the player moves or something like that

![image](https://user-images.githubusercontent.com/29390554/162104182-aeb39ec4-f6b8-470e-866e-c84fadebd5de.png)
