### ISSUE TITLE
Multiple map despawning issues

### ISSUE THREAD

**Issue by Trouv** [StarArawn/bevy_ecs_tilemap#175]
There seems to be some problems with bevy_ecs_tilemap main and despawning/clearing maps when you have multiple maps.

Here's some footage of the behavior I'm talking about: https://clips.twitch.tv/TrustworthyTemperedTarsierChocolateRain-XXJb6V--hER2io8U

There are 3 levels here, and when the player enters the top level, the bottom one is supposed to despawn, and when they enter the bottom level, the top one is supposed to despawn. However, it seems that some of the layers of the level that's supposed to stay get removed as well. This is NOT an issue when using bevy_ecs_tilemap 0.5.

For reference, here is function that gets called when despawning the maps: https://github.com/Trouv/bevy_ecs_ldtk/blob/bevy-0.7/src/systems.rs#L247. This function is followed by running `map.despawn(&mut commands)`. The despawning is handled rather manually to avoid using the MapQuery, but again, it worked fine in 0.5.

My best guess is that layers that belong to different maps get conflated with each other sometimes, ~but if that was the case I don't understand why the middle level in the footage provided doesn't seem to get affected at all.~

Turning off culling in the layer settings doesn't affect the behavior.

It could be an issue on my end, I'm gonna keep looking into it.

**Comment by Trouv** [comment]
According to bevy-inspector-egui, it doesn't look like the layers/chunks are actually getting despawned at all, so they're no longer being rendered for some other reason.

**Comment by Trouv** [comment]
Correction: the middle level's layers DO get despawned sometimes, just not in this footage.

**Comment by Trouv** [comment]
Also, after tinkering a bit it seems that this remains a problem with `MapQuery`'s despawn as well, not just my custom one.

**Comment by StarArawn** [comment]
> Also, after tinkering a bit it seems that this remains a problem with `MapQuery`'s despawn as well, not just my custom one.

I took a look at this and I was unable to reproduce, however I think I'm doing things a bit differently. Here is the code I used in the map example it worked fine:

```rust
fn remove_map(
    mut commands: Commands,
    mut map_query: MapQuery,
    keyboard_input: Res<Input<KeyCode>>,
) {
    if keyboard_input.pressed(KeyCode::Space) {
        map_query.despawn_layer(&mut commands, 0, 0);
    }
}
```

If possible could you try reproducing in one of the examples and then posting those changes here if you can reproduce?

**Comment by Trouv** [comment]
Still trying to reproduce this with a minimal example, unsuccessfully.

One more observation about this issue: it seems to actually be chunk specific. I lowered the chunk size in my plugin and the affect seems to only affect some layers of some chunks, not entire layers across a map.

I do have a smaller example that this is also affecting in bevy_ecs_ldtk: the `level_set` example. In the `tilemap_troubleshooting` branch, I've lowered the chunk size and replaced all custom despawning logic with `MapQuery::despawn` calls.

I'll keep trying to produce a minimal example in the meantime.

**Comment by Trouv** [comment]
Another observation: it seems it might be affecting the render ORDER of the layers, not actually unrendering them. The color that is overtaking some of the levels in the footage isn't the clear color, but rather the first layer of the map, which is just a single tile layer from an LDtk level's level background color value.

**Comment by Trouv** [comment]
Fixed in the PR
