### ISSUE TITLE
Tile entities are leaked upon recursively despawning the Map entity

### ISSUE THREAD

**Issue by forbjok** [StarArawn/bevy_ecs_tilemap#18]
When the Map entity is despawned with .despawn_recursive(), all tile entities belonging to that tilemap continue to exist even though they are no longer visible. As far as I can tell, this is due to the tile entities not being marked as children of the Map entity.

**Comment by forbjok** [comment]
They don't necessarily need to be children of chunks, do they?
Both chunks and tiles could all just be children of the Map entity itself.

**Comment by StarArawn** [comment]
Part of the issue with having tiles be a child of the map entity or the chunk entity is that tiles don't have standard transforms, and bevy currently complains about that. We could give them standard transforms, but then its just a lot of extra data that is not needed and people might assume that changing a tile transform would change where a tile is located which isn't supported and isn't easy to support.

**Comment by forbjok** [comment]
> tiles don't have standard transforms, and bevy currently complains about that

If that's the case, maybe we should suggest fixing it in Bevy. I don't see any reason why entities should be forced to have a Transform in order to be part of a hierarchy.

**Comment by StarArawn** [comment]
> > tiles don't have standard transforms, and bevy currently complains about that
> 
> If that's the case, maybe we should suggest fixing it in Bevy. I don't see any reason why entities should be forced to have a Transform in order to be part of a hierarchy.
Bevy relations RFC would fix this issue. :)

See:
https://github.com/bevyengine/rfcs/pull/18

**Comment by StarArawn** [comment]
@forbjok I ran some tests with this, and I discovered a performance drop almost in half due to having a parent per child. If I instead have a `map_query.despawn_layer(layer_id)` would that be acceptable?

**Comment by forbjok** [comment]
Interesting. I wonder why that would affect performance when tiles don't have transforms that would need to be propagated. Have you looked into why it's affecting performance?

**Comment by StarArawn** [comment]
The performance is mainly lost due to how `bevy_transform` propagates the transform information for parents/children. It always iterates over the children regardless of whether they have transforms or not.

**Comment by StarArawn** [comment]
You can now use `map_query.depsawn_map` to despawn an entire map including tiles. Optionally you can despawn layers with `depsawn_layer` or tiles with: `despawn_layer_tiles`.
