### ISSUE TITLE
Bevy 0.6 support

### ISSUE THREAD

**Issue by Aposhian** [StarArawn/bevy_ecs_tilemap#183]
It looks like there was development with Bevy 0.6, but no release before moving on to Bevy 0.7. It would be nice to have a stable version that supports Bevy 0.6, even if it isn't a crates.io release, at least a commit? If I wanted to craft such a version, where would be the best commit to start from? I tried e4270e1c92ff56dd343eeb75504a1dbc5577ce44 but it had a lot of compilation errors.

**Comment by StarArawn** [comment]
Bevy 0.6 is supported by `bevy_ecs_tilemap` 0.5. Here you can see the release:
https://crates.io/crates/bevy_ecs_tilemap/0.5.0
here are the dependencies:
https://crates.io/crates/bevy_ecs_tilemap/0.5.0/dependencies

**Comment by Aposhian** [comment]
Oh, I saw the table but misread it. Thanks for clarifying.
