### ISSUE TITLE
visual tearing between tiles

### ISSUE THREAD

**Issue by Aposhian** [StarArawn/bevy_ecs_tilemap#184]
I have a somewhat working example at https://github.com/Aposhian/bevy-sandbox/tree/tilemap-refactor which you can run with
```
cargo run --example tiled --release
```
There are tearing artifacts that show up between tiles that is variable as I move the camera around. This same issue occurred when I implemented without bevy_ecs_tilemap, and simply rendered each tile as a sprite.
![image](https://user-images.githubusercontent.com/16969110/164915803-2db02c5c-1654-43fb-bdf1-8d28582602c8.png)

**Comment by Aposhian** [comment]
The tileset asset is in that repo as well, and while acknowledge that it isn't a work of art, each of the tiles is indeed 32x32 pixels, but it looks like there is an off-by-one error sometimes. In that big brown area, it looks like it is incorporating a single line of another tile. Note that this issue only manifests as the camera moves: it is not consistent. For example: 
![image](https://user-images.githubusercontent.com/16969110/164916147-01c350db-f6df-4f7a-a955-7626e90023c0.png)

**Comment by StarArawn** [comment]
I noticed you are using the `Atlas` feature. Does the problem go away when you turn that feature off?

**Comment by Aposhian** [comment]
I haven't gotten my code to work without the atlas feature, but I can try playing with it and getting it to work without a TextureAtlas.

**Comment by Aposhian** [comment]
When I disabled the atlas feature, the tearing went away.

**Comment by StarArawn** [comment]
> When I disabled the atlas feature, the tearing went away.

This is because atlases cause tearing like this. You might be able to avoid the tearing by turning off MSAA in bevy.

**Comment by zicklag** [comment]
I think I've got a fix for this in #197 :crossed_fingers: 

If anybody wants to try it and see if it fixes it that would be great.
