### ISSUE TITLE
Question: GPUAnimated Exclusive to LayerBuilder?

### ISSUE THREAD

**Issue by mbolt35** [StarArawn/bevy_ecs_tilemap#199]
Thanks for the amazing project - I've had a blast building on this plugin the last few months. 

I've noticed that inserting a `GPUAnimated` component to a tile `Entity` after spawning the map (it may be as early as the `build_layer` call) no-ops. I'm assuming that this is the intentional design, and that I should just use a bevy system to advance the tile's animation?

The only downside to that approach is forcing an update of the entire chunk on each animation tick. Is there another approach that I'm missing? 

Thanks again!

**Comment by StarArawn** [comment]
I'm not sure why this would noop, can you provide a small example it might help in figuring out what is wrong.

**Comment by mbolt35** [comment]
Closing -- user mistake :)
