### ISSUE TITLE
Support using texture arrays loaded from KTX2 files

### ISSUE THREAD

**Issue by inodentry** [StarArawn/bevy_ecs_tilemap#206]
The KTX2 format natively supports array textures (and also mipmaps, texture compression, etc). Bevy should be capable of loading such files and natively representing them as an Image asset with multiple array layers.

This seems like a nice way of storing tileset assets. Better than a flat spritesheet atlas.

`bevy_ecs_tilemap` might want to support this.

It would have to detect when the Image asset is already an array texture, and skip the "atlas to array conversion" code, and use the array layers instead.

**Comment by rparrett** [comment]
This was added in #306 and the issue mistakenly not closed as far as I can tell.

Please let me know if there's still something lacking here.
