### ISSUE TITLE
Feature: Map loader

### ISSUE THREAD

**Issue by martinmolin** [StarArawn/bevy_ecs_tilemap#21]
Would it make sense to make a generic map loader trait and implement for example the loading of Tiled maps similar to your other repo bevy_tiled?

**Comment by StarArawn** [comment]
Some work is being done to move `bevy_tiled` to use `bevy_ecs_tilemap`:
https://github.com/StarArawn/bevy_tiled/pull/62

I think that is a better approach. There are also other formats that could potentially be loaded like ldtk, and I'm sure some users will want to read/write their own tilemap formats.

**Comment by martinmolin** [comment]
Yep this makes a lot of sense! Good job to everyone involved there, I missed that it was already being worked on :)
