### ISSUE TITLE
`TileStorage` needs to be aware of `TilemapMeshType` for `get_neighboring_pos` to work correctly

### ISSUE THREAD

**Issue by bzm3r** [StarArawn/bevy_ecs_tilemap#212]
Currently, the [`get_neighboring_pos`](https://docs.rs/bevy_ecs_tilemap/0.7.0/src/bevy_ecs_tilemap/tiles/storage.rs.html#50-60) method on `TileStorage` assumes that the [`TilemapMeshType`](https://docs.rs/bevy_ecs_tilemap/0.7.0/bevy_ecs_tilemap/map/enum.TilemapMeshType.html) for the tilemap in question is `Square`.

However, in order to return the neighbours correctly, `TileStorage` needs to be aware of whether the `TilemapMeshType` is of `Square` type or `Hex` type.

**Comment by StarArawn** [comment]
Related to:
https://github.com/StarArawn/bevy_ecs_tilemap/issues/94

**Comment by StarArawn** [comment]
fixed by: #228
