### ISSUE TITLE
Provide helper function to calculate coordinates of a tile in world space

### ISSUE THREAD

**Issue by bzm3r** [StarArawn/bevy_ecs_tilemap#213]
The `helpers` module currently has [`get_chunk_2d_transform`](https://docs.rs/bevy_ecs_tilemap/0.7.0/bevy_ecs_tilemap/helpers/fn.get_chunk_2d_transform.html). A very similar function, which would convert the integer coordinates of tile position into world space coordinates would be helpful. For example, if the user wants to label every tile with a text 2d bundle, they would need the position of the tile to place the label.

**Comment by rparrett** [comment]
I think this was added in 290f9d6 or so.

`TilePos::center_in_world`
