### ISSUE TITLE
TilePos should implement PartialEq

### ISSUE THREAD

**Issue by Caligari** [StarArawn/bevy_ecs_tilemap#217]
This seems almost trivial, unless I'm missing something. The previous TilePos was able to eq and ne, forcing some code changes which seem unecessary.

**Comment by Caligari** [comment]
In the meantime I've defined a wrapper:

```
pub struct EqTilePos(pub TilePos);

impl PartialEq for EqTilePos {
    fn eq(&self, other: &Self) -> bool {
        (self.0.x == other.0.x) && (self.0.y == other.0.y)
    }
    fn ne(&self, other: &Self) -> bool {
        (self.0.x != other.0.x) && (self.0.y != other.0.y)
    }
}
```
Which I can use like this:

```
if EqTilePos(mover.current_tile) != EqTilePos(other.cur_tile) {
  .. some code here ..
}
```

**Comment by Caligari** [comment]
I see there is already a fix for this, just not released to cargo yet.

**Comment by StarArawn** [comment]
Closing this as main branch now supports this and will be release with the next version. 👍
