### ISSUE TITLE
Implement `From<&TilemapGridSize>` and `From<&TilemapTileSize>` for `bevy::math::f32::Vec2`

### ISSUE THREAD

**Issue by bzm3r** [StarArawn/bevy_ecs_tilemap#221]
Through queries, users will get a reference to components. Therefore, it would be nice to provide `From<&TilemapGridSize>` and `From<&TilemapTileSize>` for `bevy::mat::f32::Vec2` (in addition to the `Into<Vec2>` already provided).

However, this might not be necessary, since it is relatively easy to dereference the references, as both `TilemapGridSize` and `TilemapTileSize` implement `Copy`.

**Comment by StarArawn** [comment]
Seems reasonable enough to me.

**Comment by StarArawn** [comment]
fixed by: #228
