### ISSUE TITLE
Inconsistant behavior for texture access between native and wasm

### ISSUE THREAD

**Issue by aoidos-bin** [StarArawn/bevy_ecs_tilemap#222]
When I run the "chunking" example natively on my computer the background is paved with green squares. When I run the same example in wasm the background squares are white.
It seems that the tiles in a texture are accessed in reverse order in wasm.

Moreover, if the texture contains a single tile, it is not displayed at all.

**Comment by StarArawn** [comment]
WASM requires you to use the atlas feature as texture arrays in webgl and wgpu are broken currently.

**Comment by aoidos-bin** [comment]
It works that way, thank you !

**Comment by bmanturner** [comment]
@StarArawn Is there anywhere I can track the progress of the texture arrays being fixed?
