### ISSUE TITLE
Replace large query tuples in `extract` and `prepare` with custom `SystemParam`s

### ISSUE THREAD

**Issue by bzm3r** [StarArawn/bevy_ecs_tilemap#225]
The queries in [`extract`](https://github.com/StarArawn/bevy_ecs_tilemap/blob/08cb16ea07d43de1acae4f5841a474337d78e16c/src/render/extract.rs#L106) and [`prepare`](https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/src/render/prepare.rs#L54) are getting quite large! We should replace them with custom [`SystemParam`](https://docs.rs/bevy/latest/bevy/ecs/system/trait.SystemParam.html#example)'s to help wtih readability/usability.

**Comment by StarArawn** [comment]
I'm not sure a `SystemParam` will make things easier. Generally I would use a `SystemParam` in a case where I need to reuse a query or a group of queries. In this case we would be moving the logic outside of where its used. 🤔

**Comment by bzm3r** [comment]
> I'm not sure a `SystemParam` will make things easier. Generally I would use a `SystemParam` in a case where I need to reuse a query or a group of queries. In this case we would be moving the logic outside of where its used. 🤔

Okay, this makes sense to me. I'll close this issue for now.
