### ISSUE TITLE
Use `bevy_pancam` as the helper camera in examples?

### ISSUE THREAD

**Issue by bzm3r** [StarArawn/bevy_ecs_tilemap#227]
`bevy_pancam` is awesome for our use case (I use it in my projects): https://github.com/johanhelsing/bevy_pancam

Should we consider using it in the examples too, instead of the current helper camera?

**Comment by StarArawn** [comment]
I'm a little hesitant to bring in a bevy plugin as a dev dependency as it might make updating to the latest bevy slower. As an example here is a crate which use to be used quite a bit, but has yet to be updated to 0.8.
https://github.com/BlackPhlox/bevy_config_cam

**Comment by bzm3r** [comment]
@StarArawn Makes sense to me! This issue can be closed then.
