### ISSUE TITLE
Add height tiles to isometric example

### ISSUE THREAD

**Issue by ekaats** [StarArawn/bevy_ecs_tilemap#23]
The isometric example only allows for flat tiles at the moment. I have a fix ready for the renderer but am still working on placing the correct tiles. For this I have to look into how the tile atlas works so I can place the correct adjacent tiles. This may make the example a lot more complicated.

**Comment by demilich1** [comment]
Cannot comment on the linked fix, but I just wanted to say that I have just encountered this issue in my project. I think this is a requirement for most isometric games, for now I have to abandon bevy_ecs_tilemap unfortunately :( Also related to #44

**Comment by StarArawn** [comment]
This should be fixed now. There are some bugs with Iso tilemaps that have height but they are being worked out.
