### ISSUE TITLE
The `game_of_life` example has a weird steady state.

### ISSUE THREAD

**Issue by bzm3r** [StarArawn/bevy_ecs_tilemap#235]
If the `game_of_life` example is kept running for a few seconds, one sees:

![image](https://user-images.githubusercontent.com/4350451/187004784-054d623d-3dff-4d52-bb64-0ae5341d3b12.png)

**Comment by StarArawn** [comment]
> If the `game_of_life` example is kept running for a few seconds, one sees:
> 
> ![image](https://user-images.githubusercontent.com/4350451/187004784-054d623d-3dff-4d52-bb64-0ae5341d3b12.png)

This is normal due to how we place the tiles. I think a better thing here is to just make the map smaller. 32x32 tiles should be more than enough space and it fits on the screen nicely.

**Comment by bzm3r** [comment]
Fixed! https://github.com/StarArawn/bevy_ecs_tilemap/commit/2773caf0e6d82ea2cf2609c6b97b0b4d4b892739
