### ISSUE TITLE
Render in isometric doesn't work correctly 

### ISSUE THREAD

**Issue by MonforteAdrian** [StarArawn/bevy_ecs_tilemap#267]
When using full cubes instead of only the top face in isometric, it doesn't render properly.
First error i found is that the order in the render for isometric is not correct it should start on the top and go left or right.
Second error is that when you use full blocks the height alignment is not correct(Its using 16px with tile size 64*64), I tried changing the spacing but it doesn't seem to work in iso.

This is the result of using the example iso_diamond with the isometric-sheet.png and TilemapTileSize x 64 and y 64

**Comment by StarArawn** [comment]
Are you talking about stacked isometric tiles? This isn't supported currently as you need to sort tiles along the Y axis and this is non-trivial to do in bevy's 2D renderer in a way that is performant.

**Comment by MonforteAdrian** [comment]
Yes, Ok thank you for the quick response.
