### ISSUE TITLE
Make sure `uv`s for the texture array-based fragment shader are not interpolated 

### ISSUE THREAD

**Issue by bzm3r** [StarArawn/bevy_ecs_tilemap#269]
Currently, we rely on casting `uv.z` as `i32`. Does this have any weird edge cases? Better thing would be to add in a flag on the `uv` that specifies it should not be interpolated. See here for an example of how to do this: https://github.com/bzm3r/doug_renderers/blob/428a400d85ba989e5f78d5d7b4eb9686334bc12c/src/shaders/vpull.wgsl#L43

**Comment by StarArawn** [comment]
Turns out this is indeed an issue. It happens when zooming the projection matrix in and out sometimes a tile uv.z can end up being 0.9999 because of interpolation and since we cast to i32 it drops the decimals leaving us with zero instead of one.
