### ISSUE TITLE
`HexCoordSystem::Column` example is broken (has a giant gap)

### ISSUE THREAD

**Issue by BoxyUwU** [StarArawn/bevy_ecs_tilemap#274]
When running `hexagon_column` if you press space to get to the axial coord system `HexCoordSystem::Column` a giant gap appears:
`hexagon_column` 
![image](https://user-images.githubusercontent.com/21149742/190880870-0c84c1cf-b5ab-465a-b980-7a2ffa76ee4b.png)

This does not show with the `hexagon_row` example using `HexCoordSystem::Row`

**Comment by bzm3r** [comment]
@BoxyUwU Thank you for bringing this to our attention! We are in the midst of an overhaul that should soon have this problem fixed robustly. 

For now, I'll get a quick fix out.
