### ISSUE TITLE
Texture filtering mode is forced to Nearest, no way to use Linear

### ISSUE THREAD

**Issue by inodentry** [StarArawn/bevy_ecs_tilemap#277]
After a quick investigation, it seems like you are hardcoding `FilterMode::Nearest` on line 282 in `src/render/mod.rs`.

Regardless of how I have configured my original Image asset, you create your texture array with your own sampler with Nearest filtering.

I want Linear filtering for my tilemap, and currently there is no way for me to override that.

**Comment by StarArawn** [comment]
We should use bevy's settings here instead. 👍

**Comment by bzm3r** [comment]
Closed by #280
