### ISSUE TITLE
WASM Support for texture arrays

### ISSUE THREAD

**Issue by aleokdev** [StarArawn/bevy_ecs_tilemap#283]
The crate doesn't seem to work with WASM, as it doesn't render anything. Tried the LDTK example and got this: 
![Screenshot_20220923_230924](https://user-images.githubusercontent.com/16354904/192057115-96da2ce2-4e1b-456b-8964-45fda6e9fa3e.png)

**Comment by StarArawn** [comment]
You need to use the `atlas` feature on WASM. There is a wgpu bug with array textures.

**Comment by aleokdev** [comment]
Works perfectly, thanks!

**Comment by bzm3r** [comment]
@StarArawn Can you link to the relevant WGPU issue here?

**Comment by StarArawn** [comment]
> @StarArawn Can you link to the relevant WGPU issue here? With that, we can close this issue, I think.

No issue that I know of. I can probably create one though. I need to collect more info though.

**Comment by musjj** [comment]
Are there any downsides/overhead to the `atlas` feature, or is it safe to just activate on all target archs?

**Comment by StarArawn** [comment]
> Are there any downsides/overhead to the `atlas` feature, or is it safe to just activate on all target archs?

There are more rendering artifacts because atlases inherently bleed neighboring pixels. Texture arrays are generally better and are supported by webGPU if that is your target.
