### ISSUE TITLE
Unable to handle large tile sets (TextureArrayCache::Prepare)

### ISSUE THREAD

**Issue by Floyden** [StarArawn/bevy_ecs_tilemap#289]
It is currently not possible to load large tile sets with the current implementation of TextureArrayCache. In TextureArrayCache::Prepare an image layer is allocated for every tile in the tile when creating a texture. Most devices only support up to 2048 image array layers and when loading a tile set with more tiles than that, the texture cannot be created. 

https://github.com/StarArawn/bevy_ecs_tilemap/blob/6fa441f6ddf93850f6219216f738283c6c174514/src/render/texture_array_cache.rs#L71-L83

**Comment by StarArawn** [comment]
4096 is supported by 99% of webgl2 gpus. For older hardware I suggest falling back to using atlases with the `atlas` feature.

**Comment by StarArawn** [comment]
> @StarArawn is it possible to create multiple texture arrays, if `count` is greater than what the hardware supports?

Yes but it becomes much more complex. Maybe in the future we can do that though.

**Comment by bzm3r** [comment]
@Floyden does the discussion here make sense to you? Does it make sense for you to use the `atlas` feature instead?

**Comment by Floyden** [comment]
I enabled the `atlas` feature, and it seems to work now. However, I don't really know what the drawbacks or the major differences of enabling that feature are, since there is not really any documentation of that feature.

**Comment by bzm3r** [comment]
Okay, thanks, we'll make an issue off of that and close this one.
