### ISSUE TITLE
Derive Reflect and Register Types for Scene Support

### ISSUE THREAD

**Issue by zicklag** [StarArawn/bevy_ecs_tilemap#298]
I'm thinking of creating a map editor where I want to be able to save maps to a Bevy scene after editing them in the game. This requires implementing reflect on all the relevant components and registering their types. Is this something you are open to a PR for?

**Comment by bzm3r** [comment]
@zicklag I can't speak on StarToaster's behalf, but this definitely seems interesting to me. What are the downsides or "need-to-knows" of deriving Reflect on various bevy_ecs_tilemap components?

**Comment by zicklag** [comment]
I don't think there are really any downsides or things that anybody would need to know unless they were interested in the extra functionality.

It's pretty much invisible unless you try to use it, and Bevy itself is starting to derive reflect and register all of it's components I believe, which makes them compatible with things like [bevy-inspector-egui](https://github.com/jakobhellermann/bevy-inspector-egui)'s world inspector and upcoming scripting solutions like [bevy_mod_js_scripting](https://github.com/jakobhellermann/bevy_mod_js_scripting).

I did change my mind, I think, about using the scene export to establish an editor, though, because I realized that if I had maps generated with an older version of the game, and possibly a different set of components on tiles, it would be harder to migrate the old maps to the new format than if I used a custom YAML format for the map instead.

So I might not need this yet, we'll see, but it'd probably still be something good to do eventually.

**Comment by StarArawn** [comment]
I'm up for this, but I think we would possibly want to feature gate it? 

I was at one point designing a 2d tile map editor for bevy. I have some figma designs but I haven't worked on them recently.

**Comment by zicklag** [comment]
It wouldn't hurt to put it behind a feature flag. Since it's probably harmless we could probably make it a default feature, too, so that people who are really worried about it can disable it, but other people will get the integration advantages by default.

**Comment by StarArawn** [comment]
> It wouldn't hurt to put it behind a feature flag. Since it's probably harmless we could probably make it a default feature, too, so that people who are really worried about it can disable it, but other people will get the integration advantages by default.

After looking at bevy's reflect stuff I don't think we need to put it behind a feature flag. Reflect comes as part of bevy core so it should be "free" for us to add.
