### ISSUE TITLE
Add `TilePos::from_cursor_pos`

### ISSUE THREAD

**Issue by alice-i-cecile** [StarArawn/bevy_ecs_tilemap#305]
As demonstrated in the `neighbors.rs` example, you need to do some fancy math to get the world position from the cursor position.

We should have an API which handles this for you, to supplement `TilePos::from_world_pos`.

**Comment by StarArawn** [comment]
I agree that it's complicated but I don't think it is something that `bevy_ecs_tilemap` should provide. It feels out of scope. I think this is something that would be great to have native bevy support for. Alternatively we could possibly look into using `bevy_mod_picking` by adding 2d support.

**Comment by frederickjjoubert** [comment]
> I agree that it's complicated but I don't think it is something that `bevy_ecs_tilemap` should provide. It feels out of scope. I think this is something that would be great to have native bevy support for. Alternatively we could possibly look into using `bevy_mod_picking` by adding 2d support.

I disagree that it is out of scope. I think it is a common enough use case with games that use Tiles that `bevy_ecs_tilemap` should include it.

**Comment by StarArawn** [comment]
> > I agree that it's complicated but I don't think it is something that `bevy_ecs_tilemap` should provide. It feels out of scope. I think this is something that would be great to have native bevy support for. Alternatively we could possibly look into using `bevy_mod_picking` by adding 2d support.
> 
> I disagree that it is out of scope. I think it is a common enough use case with games that use Tiles that `bevy_ecs_tilemap` should include it.

It is a common use case, but camera's are controlled by bevy not by `bevy_ecs_tilemap`. I think an example of how it works is sufficient enough until bevy can provide a generic way of handling this. I think my biggest point here is that the work should be done in bevy and then used in the `bevy_ecs_tilemap` examples. If I offer a very specific mouse to tile function that does little for any of bevy's 2D stuff and will only work for `bevy_ecs_tilemap`, but if the work was done in bevy directly then it can be reused to also allow sprite mouse picking within bevy.

**Comment by rparrett** [comment]
I think this was largely solved when Bevy added `viewport_to_world_2d`.

It's super simple to get this now.
