### ISSUE TITLE
Rename `TileTexture` to `TileTextureIndex` or `TextureIndex`

### ISSUE THREAD

**Issue by frederickjjoubert** [StarArawn/bevy_ecs_tilemap#321]
I think we should rename `TileTexture` to `TileTextureIndex` or `TextureIndex`

It is confusing that the name indicates a texture when it is just an index to a texture:

[https://docs.rs/bevy_ecs_tilemap/latest/bevy_ecs_tilemap/tiles/struct.TileTexture.html](https://docs.rs/bevy_ecs_tilemap/latest/bevy_ecs_tilemap/tiles/struct.TileTexture.html)

It would also improve naming clarity here:

[https://docs.rs/bevy_ecs_tilemap/latest/bevy_ecs_tilemap/tiles/index.html](https://docs.rs/bevy_ecs_tilemap/latest/bevy_ecs_tilemap/tiles/index.html)

**Comment by StarArawn** [comment]
Lets go ahead and do this. 👍 Feel free to open a PR, or I'll get to it in a few days.

**Comment by frederickjjoubert** [comment]
I am happy to do it.

**Comment by StarArawn** [comment]
This is finished closing this issue now.

@frederickjjoubert Thank you for the PR!
