### ISSUE TITLE
Hardcoded TextureFormat

### ISSUE THREAD

**Issue by martinmolin** [StarArawn/bevy_ecs_tilemap#334]
While setting up a project using `bevy_ecs_tilemap` I ran into an issue where my textures has a different format compared to what is expected by the crate leading to wgpu throwing a validation error:
```rs
ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default
thread 'Compute Task Pool (9)' panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_texture
    Copy error
    source format (Bc1RgbaUnormSrgb) and destination format (Rgba8UnormSrgb) are different
```

This seems to be because of [this](https://github.com/StarArawn/bevy_ecs_tilemap/blob/edaa754c34d5ed46d3d283ad53b62dd6fbbf782d/src/render/texture_array_cache.rs#L152).

As discussed in [this Discord help thread](https://discord.com/channels/691052431525675048/1035279080083427378) it might be possible to read the format of the texture instead of assuming `Rgba8UnormSrgb`. Possibly check that all textures also have the same format.

**Comment by StarArawn** [comment]
Fixed by: #335
