### ISSUE TITLE
LDTK, large map issue

### ISSUE THREAD

**Issue by KjartanKlein** [StarArawn/bevy_ecs_tilemap#35]
When attempting to load maps that are larger than 512px in any dimensions the program returns a panic.
` thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfBounds', /home/kl/.cargo/git/checkouts/bevy_ecs_tilemap-8c720d5970222b21/2a60b2a/src/ldtk.rs:177:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Segmentation fault (core dumped)
`
I have tried to see what is exactly wrong, but cant seem to figure it out.

**Comment by StarArawn** [comment]
This is fixed by: #36
