### ISSUE TITLE
TilemapSpacing is broken when using atlas feature

### ISSUE THREAD

**Issue by rparrett** [StarArawn/bevy_ecs_tilemap#352]
### Version tested

MacOS (M1)
main branch

### Problem

However, it seems that when using the atlas texture renderer, both tilemaps look very broken, but in different ways.

`cargo run --example spacing --features=atlas`
<img width="1270" alt="atlas" src="https://user-images.githubusercontent.com/200550/203448077-fd7bbb72-84c2-4d40-a8c1-dd997493fa87.png">

**Comment by dogue** [comment]
I'm not sure if it's related, but I ran into a bug with using array textures vs atlas textures when the tilesheet has spacing between tiles but not around the outer edges of the sheet. When using array, a 16x16 grid size with 16x16px tiles would obscure parts of the tiles. When using the atlas feature, the tiles render as expected with no gaps or overlaps.

**Comment by rparrett** [comment]
I split out the non-atlas-related bits of this bug report into #364.
