### ISSUE TITLE
Contributing Guide?

### ISSUE THREAD

**Issue by Andrew-Pynch** [StarArawn/bevy_ecs_tilemap#371]
Hey! I absolutely love this library and want to help out. Not sure where the best place to start is. What are your standards for contributing, and what areas could I have the most impact in right now.

**Comment by StarArawn** [comment]
> Hey! I absolutely love this library and want to help out. Not sure where the best place to start is. What are your standards for contributing, and what areas could I have the most impact in right now.

Contributions are welcome! There currently is no guide sadly, but a running theme is to just pick an issue from the backlog and work on it. Or if there is something you want changed/fixed open up a PR. 

I'm pretty selective about large PR's or very opinionated PR's, but I've worked in the past with people to get stuff merged in. 👍 

As far as future goals right now I think a big one is to:

1. Fix existing bugs
2. Re-write renderer to support:
  a. Custom shaders
  b. Feature locked rendering modes(Vertex pulling or regular mesh rendering).
