### ISSUE TITLE
Should `fill_tilemap` be adding tiles as children to the tilemap entity?

### ISSUE THREAD

**Issue by SirHall** [StarArawn/bevy_ecs_tilemap#375]
`fill_tilemap` causes the `bench` command to take a *very* long time to load (long enough that I don't actually know).
If we look at its definition in filling.rs:
```rust
/// Fills an entire tile storage with the given tile.
pub fn fill_tilemap(
    texture_index: TileTextureIndex,
    size: TilemapSize,
    tilemap_id: TilemapId,
    commands: &mut Commands,
    tile_storage: &mut TileStorage,
) {
    for x in 0..size.x {
        for y in 0..size.y {
            let tile_pos = TilePos { x, y };
            let tile_entity = commands
                .spawn(TileBundle {
                    position: tile_pos,
                    tilemap_id,
                    texture_index,
                    ..Default::default()
                })
                .id();
            commands.entity(tilemap_id.0).add_child(tile_entity);
            tile_storage.set(&tile_pos, tile_entity);
        }
    }
}
```

The culprit from my testing has been `commands.entity(tilemap_id.0).add_child(tile_entity);`.
Without that line the benchmark launched in a mere few seconds, not very methodical - but it works.

One option is to take the loop, pull out the `commands.entity(tilemap_id.0).add_child(tile_entity);` call, switch to using `add_children` and place the loop inside that:
```rust
/// Fills an entire tile storage with the given tile.
pub fn fill_tilemap(
    texture_index: TileTextureIndex,
    size: TilemapSize,
    tilemap_id: TilemapId,
    commands: &mut Commands,
    tile_storage: &mut TileStorage,
) {
    let mut tilemap = commands.entity(tilemap_id.0);
    tilemap.add_children(|parent| {
        for x in 0..size.x {
            for y in 0..size.y {
                let tile_pos = TilePos { x, y };
                let tile_entity = {
                    parent
                        .spawn(TileBundle {
                            position: tile_pos,
                            tilemap_id,
                            texture_index,
                            ..Default::default()
                        })
                        .id()
                };
                tile_storage.set(&tile_pos, tile_entity);
            }
        }
    });
}
```

This fixes the loading issue and now `bench` loads quickly again.
Only issue is that while perusing the other `fill*` functions I noticed that none of them add the newly spawned tiles as children to the tilemap entity.

Is this an oversight, and should we be fixing all the other filler functions, is it not needed and rather should we be taking it out of `fill_tilemap`?

In either case, there is a pretty simple solution to `bench`'s loading time.

**Comment by bzm3r** [comment]
@SirHall Yeah, you're right. We don't need to be adding the tiles as children of the tilemap!

**Comment by StarArawn** [comment]
We should be using `add_children` as it's much faster.
