### ISSUE TITLE
Read Me Typo (Maybe?)

### ISSUE THREAD

**Issue by HyperAlch** [StarArawn/bevy_ecs_tilemap#386]
On your README.md page under examples it says the following:

[animation](https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/examples/animation.rs) – Basic CPU animation example.

Do you guys mean GPU animation? I'm not sure why we would use a CPU for animation. Please let me know if I'm wrong. And if I'm wrong and this is indeed a CPU Animation example, can you please point me in the direction of a GPU example.

**Comment by StarArawn** [comment]
Looks like a legacy thing. At one point animations were CPU only, but I added GPU based animations.
