### ISSUE TITLE
Maps that aren't square and a power of 2 create many empty entities

### ISSUE THREAD

**Issue by Elabajaba** [StarArawn/bevy_ecs_tilemap#39]
Having a chunk_size or a map_size that isn't both square and a power of 2 creates many empty entities.
Eg. 
```
let layer_settings = LayerSettings::new(
    UVec2::new(1, 1),
    UVec2::new(4, 2),
    Vec2::new(16.0, 16.0),
    Vec2::new(96.0, 256.0),
);
```
will create 8 empty entities (I assume for padding), while 
```
let layer_settings = LayerSettings::new(
    UVec2::new(1, 1),
    UVec2::new(4, 4),
    Vec2::new(16.0, 16.0),
    Vec2::new(96.0, 256.0),
);
```
will not create any empty entities.

I don't really care about the extra memory usage, but it makes the WorldInspectorPlugin from https://github.com/jakobhellermann/bevy-inspector-egui unusable on mid-large maps that aren't perfect power of 2 squares because it pollutes the inspector with a ton of garbage empty entities, and as far as I know you also can't filter them out using a query. 

eg. I use ```.add_plugin(WorldInspectorPlugin::new().filter::<Without<Tile>>())``` due to performance issues with huge lists of entities in bevy-inspector-egui, but due to the empty entities I'm left with a ton of entities I can't filter out without making maps bigger and/or non rectangular so they're all perfect power of 2 squares.

**Comment by StarArawn** [comment]
In hindsight this seems like something I should have never been an issue in the first place, but I was iterating over LayerBuilder quite a bit. We can fix this by making a small change to `LayerBuilder` by removing the spawn code here:
https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/src/layer_builder.rs#L49

I think instead we wait to spawn tiles until we get to `build` or in `get_tile_entity` that should allow us to not have extra entities spawning everywhere. 🤔

Optionally you can implement a fix for this now in your own code by using `new_batch` as it will only spawn entities for tiles that actually exist. You can see an example of that here:
https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/examples/bench.rs#L22

**Comment by StarArawn** [comment]
@Elabajaba Can you test out #41 and see if that fixes your issues? :)

**Comment by Elabajaba** [comment]
Yup, that fixed it for me.
