### ISSUE TITLE
Tile textures get re-copied every frame, even when not updated

### ISSUE THREAD

**Issue by tec27** [StarArawn/bevy_ecs_tilemap#391]
I've been noticing some bad performance when using a large amount of textures (1000+) for my tiles, and looking at RenderDoc, it seems mostly related to copying texture data into images on the GPU. I'd expect that to happen once, when the tilemap is initialized, and then only have updated textures copied over after that, but it seems to happen every frame for every texture even when nothing has changed.

This also seems to happen in all of the examples I've tried. The tell-tale sign is `vkCmdCopyBufferToImage` for the tile images:

![image](https://user-images.githubusercontent.com/360513/219971208-c876b593-01b8-4e42-a825-1f023e7a3379.png)

(Image from RenderDoc for the `tiled` example)

This also seems to happen for all the other examples I've tried (including `basic`), so I'm not sure that it relates to a particular `TilemapTexture` type

**Comment by tec27** [comment]
I did a little more digging on this (still not at a place where I have an idea of what's wrong but getting *somewhere*).

When running the basic example, an `AssetEvent::Changed` is being posted every frame for the tile texture. I determined this by adding a `RenderStage::Extract` system:

```rs
fn changed_render_asset(
    mut events: Extract<EventReader<AssetEvent<Image>>>,
    assets: Extract<Res<Assets<Image>>>,
) {
    let mut created_assets = HashSet::default();
    let mut changed_assets = HashSet::default();
    for event in events.iter() {
        match event {
            AssetEvent::Created { handle } => {
                created_assets.insert(handle.clone_weak());
            } AssetEvent::Modified { handle } => {
                changed_assets.insert(handle.clone_weak());
            }
            _ => {}
        }
    }

    for handle in created_assets.drain() {
        if let Some(asset) = assets.get(&handle) {
            debug!("Created asset with size: {:?}", asset.texture_descriptor.size);
        }
    }
    for handle in changed_assets.drain() {
        if let Some(asset) = assets.get(&handle) {
            debug!("Changed asset with size: {:?}", asset.texture_descriptor.size);
        }
    }
}

struct DebugPlugin;

impl Plugin for DebugPlugin {
    fn build(&self, app: &mut App) {
        let render_app = app.sub_app_mut(RenderApp);
        render_app.add_system_to_stage(RenderStage::Extract, changed_render_asset);
    }
}
```

**Comment by StarArawn** [comment]
This is where the array textures copy is queued:
https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/src/render/texture_array_cache.rs#L301

**Comment by tec27** [comment]
It's not actually from that, the texture copy is happening because Bevy is seeing that the asset was modified (so Bevy is the one queuing it). I found the issue though:

https://github.com/StarArawn/bevy_ecs_tilemap/blob/3171dcb02bf3ef0183727d507005cfd354e708c6/src/render/mod.rs#L258

`set_texture_to_copy_src` runs for every image that's a `TilemapTexture`, calling `set_images_to_copy_src` which:

https://github.com/StarArawn/bevy_ecs_tilemap/blob/3171dcb02bf3ef0183727d507005cfd354e708c6/src/map/mod.rs#L156

calls `get_mut` on the asset (whether or not it needs to be modified), thereby triggering an `AssetEvent::Modified` that makes the texture get reuploaded in the render phase. Easy fix is probably to call `get` instead, figure out which assets (if any) need to be updated, and then only `get_mut` those specific ones?
