### ISSUE TITLE
Error in the tiled.rs

### ISSUE THREAD

**Issue by NovaProtocol** [StarArawn/bevy_ecs_tilemap#394]
I'm editting the tiled.rs myself because there are some functions that are not yet updated but I can't get through this part

It's either this error
```rs
|     tile_storage_query: Query<(Entity, &TileStorage)>,
|                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `bevy::prelude::Component` is not implemented for `bevy_ecs_tilemap::tiles::TileStorage`
 ```
 or this error
 ```rs
|     tile_storage_query: Query<(Entity, TileStorage)>,
|                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `WorldQuery` is not implemented for `bevy_ecs_tilemap::tiles::TileStorage
 ```
 The second one is definitely will not work but I'm not sure why the first one doesn't.
 
 Using bevy 0.9.1 and main bevy_ecs_tilemap

**Comment by gungim** [comment]
Hey, i got the same error, how did you slove this error?

**Comment by rparrett** [comment]
That class of error: stuff like "The thing that is obviously a Component isn't a Component" is indicative of there being two versions of Bevy on your dependency tree.

You can use `cargo tree` to get to the bottom of that.

The main branch of this repository is currently compatible with Bevy 0.10 (crates.io release hopefully coming soon). For other versions of bevy, see the [compatibility table](https://github.com/StarArawn/bevy_ecs_tilemap#bevy-compatibility).
