### ISSUE TITLE
`despawn_layer()` takes only one type of `Into<u16>` instead of two

### ISSUE THREAD

**Issue by TheLeonsver1** [StarArawn/bevy_ecs_tilemap#42]
We should have `despawn_layer` and similar functions be on `<T1,T2> where T1:Into<u16>,T2:Into<u16>` and not on `<T:Into<u16>>`, I expect the types for the `layer_id` and the `map_id` to be different ones and the API can not accommodate that currently.

**Comment by StarArawn** [comment]
Is fixed by #43
