### ISSUE TITLE
Adding Object Layers from Tiled .tmx files

### ISSUE THREAD

**Issue by vinnyhoward** [StarArawn/bevy_ecs_tilemap#435]
I have followed the [Tiled example](https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/examples/helpers/tiled.rs) and was able to render the map just fine. But I am having issues adding Tiled's [Object Layers](https://doc.mapeditor.org/en/stable/manual/objects/) into my map to use for my collision logic and entity spawn logic. I have made small adjustments into the [Tiled example](https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/examples/helpers/tiled.rs) and have been able to render the Object but they aren't spawning at the right coordinates and they are slightly larger than the tiles compared to how they are in the Tiled editor. Does anyone have suggestions?

Here is my code below that I have added into the example. I am open to different ways of adding them as well:

```rust
    tiled::LayerType::Objects(object_group) => {
        for object in object_group.objects() {
            match &object.shape {
                tiled::ObjectShape::Rect { width, height } => {
                    let collision_shape = CollisionShape::Rect {
                        width: *width,
                        height: *height,
                    };
                    
                    let transform_position = get_tilemap_center_transform(
                        &map_size,
                        &grid_size,
                        &map_type,
                        layer_index as f32,
                    ) * Transform::from_xyz(object.x, object.y, 0.0);
                    

                    commands.spawn((
                        transform_position,
                        GlobalTransform::default(),
                        TileCollider {
                            shape: collision_shape,
                        },
                    ));
                }
                tiled::ObjectShape::Ellipse { width, height } => {
                    println!("Found an ellipse object at x: {}, y: {}, width: {}, height: {}", object.x, object.y, width, height);
                }
                tiled::ObjectShape::Polygon { points } => {
                    println!("Found a polygon object with the following points: {:?}", points);
                }
                tiled::ObjectShape::Polyline { points } => {
                    println!("Found a polyline object with the following points: {:?}", points);
                }
                _ => {
                    println!("Found an object of a type not handled in this example.");
                }
            }
        }
    }
```

**Comment by StarArawn** [comment]
This is out of scope for what this library supports. I believe you can scale objects inside of tiled. Also objects can be grouped together and groups can have position/scale. See there:
https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#objectgroup
