### ISSUE TITLE
Future: advanced isometric view

### ISSUE THREAD

**Issue by mattdm** [StarArawn/bevy_ecs_tilemap#44]
Unlike in a top-down or side view game, In many (most?) isometric games, objects represented by a tile may be taller than the actual tile space. (Like, a  tree or a wall.)

From [chat](https://discord.com/channels/691052431525675048/810632276701347920):

> StarToaster
> 
> I have given some thought on how to achieve that. A couple of steps need to happen for that to work:
> 1. Allow isometric tiles to render larger then the actual tile grid size as this allows tiles to kind of overlap each other. You would also use the rendered size for mouse picking.
> 2. Each layer is rendered top down by splitting each horizontal row into is own layer this insures that tiles are rendered correctly. > Another option would be to also calculate the z-index as being Y. This adds the further benefit of allowing sprites on the isometric tile map to render "behind" tiles. This is very similar to how some isometric games actually function(project hospital is one example).
> I don't know when I'll be able to find the time to add those things to bevy_ecs_tilemap, it certain is possible for someone to mostly do all of this currently except for point 1.

**Comment by mattdm** [comment]
And extra-advanced: isometric _hexagonal_ maps.

**Comment by StarArawn** [comment]
This is not going to be supported in `bevy_ecs_tilemap` for now. Please message me on discord if you would like more information.
