### ISSUE TITLE
Tiled example helper loses track of entities for multi-tileset maps

### ISSUE THREAD

**Issue by B-Reif** [StarArawn/bevy_ecs_tilemap#441]
In the [tiled example](https://github.com/StarArawn/bevy_ecs_tilemap/blob/1bdc8d3aa18006b2a0868da8661baee7ee351b52/examples/helpers/tiled.rs#L56C1-L61C1) we define a `HashMap` of indices to layer entities: 

```rs
pub struct TiledLayersStorage {
    pub storage: HashMap<u32, Entity>,
}
```

Later, when processing the Tiled maps, we have to iterate through each layer for each tileset imported, for reasons described [in this comment](https://github.com/StarArawn/bevy_ecs_tilemap/blob/1bdc8d3aa18006b2a0868da8661baee7ee351b52/examples/helpers/tiled.rs#L234C1-L238C96):
```rs
for (tileset_index, tileset) in tiled_map.map.tilesets().iter().enumerate() {
  // ... setup tileset ...
  for (layer_index, layer) in tiled_map.map.layers().enumerate() {
    // ... setup layer ...
    
    // The layer is stored only by this layer_index, overwriting the value set in the previous iteration of the _outer_ loop.
    layer_storage.storage.insert(layer_index as u32, layer_entity);
  }
}
```
For `n` tilesets, this code loses track of the first `n - 1` layer entities it creates.

To fix this, we could index them by both tileset id and layer index:
```rs
pub struct TiledLayersStorage {
    pub storage: HashMap<(u32, u32), Entity>,
}
```

It seems a little clunky to try to query this by a tileset index, so I think I would prefer to store a `Vec`:
```rs
// Still keyed by layer index, now with multiple matching entities:
pub struct TiledLayersStorage {
    pub storage: HashMap<u32, Vec<Entity>>,
}
```

**Comment by StarArawn** [comment]
Its not designed for this welcome to open a PR for it though. 👍
