### ISSUE TITLE
Render chunks with tilemap Entity generation > 0 are not visible

### ISSUE THREAD

**Issue by rparrett** [StarArawn/bevy_ecs_tilemap#450]
```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
SystemInfo { os: "MacOS 13.4.1 ", kernel: "22.5.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
```

bisected to 7f5113adf8851d654adc145e54b062bcb15d12b5

I remember noticing this here: https://github.com/StarArawn/bevy_ecs_tilemap/pull/428#issuecomment-1548712692 but can't recall if there was a fix that maybe didn't survive a merge or something.

## Repro

`cargo run --example chunking`

Hold the`w` key. Newly spawned chunks after the initial setup mostly do not display.

![chunking](https://github.com/StarArawn/bevy_ecs_tilemap/assets/200550/b8f7be5b-d3b8-4112-becc-aec4b414b232)

**Comment by rparrett** [comment]
Still not sure what's going on here, but I have a few observations:

- New chunks seem to be spawned, and old chunks despawned, but new chunks do not render (most of the time)
- Same issue is present with the `atlas` feature.
- The example "works" (all tilemaps are displayed) if you remove the despawning of far-away chunks.
- Same issue is present when using `MyMaterial` from the `custom_shader` example with its handle stored in a resource.

**Comment by brandon-reinhart** [comment]
Not sure if related, but I noticed that my layer 0 in a multi-layer Tiled map won't render if I have some combinations of totally unrelated despawn_recursive's happen prior and when I examine the map the texture handle on that first layer seems borked. I will try and produce a minimal example. It's kind of in that territory of "might be related, but might be something my particular game's code is doing differently." Without any other changes, it worked fine prior to 0.11.

**Comment by rparrett** [comment]
Another bizarre observation:

Only tilemap entities with a generation of `0` show up.

![image](https://github.com/StarArawn/bevy_ecs_tilemap/assets/200550/1c323988-40ce-406d-96f3-f63a79e95dfa)
