### ISSUE TITLE
"broken" behaviour on version 0.11

### ISSUE THREAD

**Issue by Elogain** [StarArawn/bevy_ecs_tilemap#453]
When using bevy 0.11 and bevy_ecs_tilemap 0.11 some broken behaviour can happen, resulting in no tilemap being rendered.

It took me a few hours of diddling around when I noticed that if I ran my generation of tilemap (basically the color example) at the startup before anything else it would display. If I did it later, in some other state onEnter it wouldnt display anything.

I checked if there had been any new commits since the 0.11 release. There was, this one specifically; https://github.com/StarArawn/bevy_ecs_tilemap/commit/b87874e9f0598176aaedf4d875927eb668312c30
I changed the dependency to being git = "" latest master and now it worked as expected.

Can we please have a 0.11.1 release as it seems to me that 0.11 is broken?

**Comment by digitalbricklayer** [comment]
Can confirm the problem with displaying the tilemap when the tilemap is not rendered immediately in v0.11.

**Comment by Biped-Potato** [comment]
Can also confirm, when updating to v0.11 and changing some code only my first room in my game would render, then with the exact same code(aside from bevy migration changes) the other rooms rendered after downgrading again.

**Comment by rparrett** [comment]
Yep, this was fixed in https://github.com/StarArawn/bevy_ecs_tilemap/pull/451 but StarArawn hasn't been able to get a patch release out yet.

You can set your `bevy_ecs_tilemap` dependency to pull from git in the meantime.

**Comment by MeoMix** [comment]
Can this issue be closed now? #451 has been merged for a while

**Comment by StarArawn** [comment]
Yep let's get this closed.
