### ISSUE TITLE
Isometric overlapping tiles have wrong priority

### ISSUE THREAD

**Issue by CiderSlime** [StarArawn/bevy_ecs_tilemap#458]
I have grass tiles of size ```{ x: 64.0, y: 48.0 }```
![Original tiles](https://github.com/StarArawn/bevy_ecs_tilemap/assets/8264131/77107bf1-3839-4099-bac9-529acee0dab6)

And I am trying to overlap them using grid size of ```TilemapGridSize { x: 64.0, y: 40.0 }```
![rendered map with overlapping tiles](https://github.com/StarArawn/bevy_ecs_tilemap/assets/8264131/156970a8-43e5-43be-80f6-8049b7220415)

The problem is, that SW side of each tile is visible. Default priority order of tiles is shadowy and lacks way to be managed manually.

P.S. On larger maps I have some rows that have desired priority, but don't understand why it happens.
![image](https://github.com/StarArawn/bevy_ecs_tilemap/assets/8264131/555b2f3c-6ea4-446c-be9d-7a01160c542b)

My suggestion is to add z-coord somewhere in ```TileBundle```, which defaults to 0.0, to make possible to adjust visibility order when neccesary. Currently setting z-coord is possible only for whole ```TileMapBundle```.
Or suggest another workaround if I'm doing it wrong.

**Comment by CiderSlime** [comment]
Test project:
https://github.com/CiderSlime/bevy_test_2d/blob/master/src/plugins/map.rs

**Comment by StarArawn** [comment]
these are 3D iso tiles please look at the 3d iso example:
https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/examples/3d_iso.rs

**Comment by CiderSlime** [comment]
The 3D isometric example, in fact, is another one Tiled example. This can be of limited help when my level is procedurally generated.

**Comment by StarArawn** [comment]
> The 3D isometric example, in fact, is another one Tiled example. This can be of limited help when my level is procedurally generated.

Sorry it took awhile to get back to you on this. The tiled example can help but you are right its not great. 

The specific piece that is important is turning on y-sorting for isometric. This has a performance cost so please keep that in mind. You'll need to use these settings:
```rust
        .insert_resource(TilemapRenderSettings {
            // Map size is 12x12 so we'll have render chunks that are:
            // 12 tiles wide and 1 tile tall.
            render_chunk_size: UVec2::new(3, 1),
            y_sort: true,
        })
 ```
