### ISSUE TITLE
Tiles are rendered smaller than expected

### ISSUE THREAD

**Issue by Lazzu** [StarArawn/bevy_ecs_tilemap#471]
I have 16x16 tiles from Kenney asset pack and I'm trying to render a map with them. I set the tile size and grid size to 16x16 and spacing as 1x1 as the texture from the asset pack has that, but the render result is different than expected.

Rendered:
![image](https://github.com/StarArawn/bevy_ecs_tilemap/assets/533938/dc5c120a-f489-4337-96d0-fbff863dc39f)
![image](https://github.com/StarArawn/bevy_ecs_tilemap/assets/533938/ed00c344-9e5a-4657-8d24-0f1e78991b7d)

Source asset:
![image](https://github.com/StarArawn/bevy_ecs_tilemap/assets/533938/6d88c28d-e121-40d1-a8d6-13417b7aa93a)

Code:
```rs
fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn(Camera2dBundle::default());
    
    let texture_handle: Handle<Image> = asset_server.load("textures/tiles/roguelikeSheet_transparent.png");

    let map_size = TilemapSize { x: 30u32, y: 20u32 };
    let mut tile_storage = TileStorage::empty(map_size);
    let tilemap_entity = commands.spawn_empty().id();

    fill_tilemap(
        TileTextureIndex(5), 
        map_size, 
        TilemapId(tilemap_entity), 
        &mut commands, 
        &mut tile_storage
    );

    let tile_size = TilemapTileSize { x: 16.0, y: 16.0 };
    let grid_size = tile_size.into();
    let tile_spacing: TilemapSpacing = TilemapSpacing { x: 1.0, y: 1.0 };
    let map_type = TilemapType::Square;

    commands.entity(tilemap_entity).insert(TilemapBundle {
        grid_size,
        map_type,
        size: map_size,
        spacing: tile_spacing,
        storage: tile_storage,
        texture: TilemapTexture::Single(texture_handle),
        tile_size,
        transform: get_tilemap_center_transform(&map_size, &grid_size, &map_type, 0.0),
        ..default()
    });

}
```

The code produces the render result where the grid is correct size but the tiles rendered in the grid are one pixel too small on each dimension.

My cargo.toml deps:
```
[dependencies]
bevy = {version="0.11.2", features=["wayland"]}
bevy_ecs_tilemap = "0.11.0"
```

The issue persists if I use the main branch:
```
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap.git", branch = "main" }
```

**Comment by StarArawn** [comment]
I took a quick look at this and the tile sizes are 15x15:
![image](https://github.com/StarArawn/bevy_ecs_tilemap/assets/6656977/012fd247-579f-422a-9211-db7c6bb8a628)
But they are 44px in the asset screenshot:
![image](https://github.com/StarArawn/bevy_ecs_tilemap/assets/6656977/821eec56-f86e-4149-ba6f-2ff95fbe010c)

Keep in mind spacing means equal spacing on the left, right, top, and bottom.

**Comment by Lazzu** [comment]
> But they are 44px in the asset screenshot
The screenshot is a zoomed-in view of the asset, the white lines mark the edges of a pixel. The asset is 16x16 if you count the pixels.

**Comment by rparrett** [comment]
You will need to add 1px of padding around the entire sheet.

The lack of support for "padding-less" sheets is tracked here: https://github.com/StarArawn/bevy_ecs_tilemap/issues/353

**Comment by Lazzu** [comment]
> You will need to add 1px of padding around the entire sheet.
> 
> The lack of support for "padding-less" sheets is tracked here: #353

Thanks, adding 1px padding around the source asset fixed the issue
