### ISSUE TITLE
Tile Color is wrong, because of sRGB/linear not being handled correctly

### ISSUE THREAD

**Issue by inodentry** [StarArawn/bevy_ecs_tilemap#479]
When using the TileColor to colorize the sprites, the colors look wrong. They look pale/light, which is indicative of missing gamma correction. sRGB is probably not set correctly in the tilemap shader.

Here is a screenshot rendered using Bevy Sprites (correct colors):

<img width="912" alt="Screenshot 2023-10-14 at 17 34 00" src="https://github.com/StarArawn/bevy_ecs_tilemap/assets/40234599/b5f6432f-f91f-40a9-9575-d04e8076945a">

Here is a screenshot rendered using Tilemap (incorrect colors):

<img width="912" alt="Screenshot 2023-10-14 at 17 30 31" src="https://github.com/StarArawn/bevy_ecs_tilemap/assets/40234599/2ce5f1fb-8a97-47a5-8b6a-78007f2d36d3">

I can apply the following workaround when setting the TileColor value, to manually "correct" the RGB values:

```rust
        let my_color = /* ... */;
        let rgba = my_color.as_linear_rgba_f32();
        tile_color.0 = Color::rgba(rgba[0], rgba[1], rgba[2], rgba[3]);
```

Now the color looks correct, the same as with Bevy Sprites. This indeed confirms that the issue is the tilemap rendering is missing sRGB handling.

**Comment by rparrett** [comment]
Are the grey tiles in your image the base color that the color is being applied to?

I think that this is maybe not an issue with "coloring tiles" but with the underlying texture colors.

**Comment by rparrett** [comment]
Hm, nevermind. This does seem to only happen when coloring is involved.

**Comment by rparrett** [comment]
<details>
  <summary>Here's a little in-repo reproducer</summary>

```rust
use bevy::prelude::*;
use bevy_ecs_tilemap::prelude::*;

mod helpers;

fn startup(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn(Camera2dBundle::default());

    let color = Color::rgba(0.3, 1.0, 1.0, 1.0);
    let rgba = color.as_linear_rgba_f32();
    let corrected = Color::rgba(rgba[0], rgba[1], rgba[2], rgba[3]);

    let texture_handle: Handle<Image> = asset_server.load("tiles.png");

    let tile_size = TilemapTileSize { x: 16.0, y: 16.0 };

    // colored
    commands.spawn(SpriteBundle {
        sprite: Sprite { color, ..default() },
        texture: asset_server.load("tiles.png"),
        transform: Transform::from_xyz(0., -40., 10.),
        ..default()
    });
    // uncolored
    commands.spawn(SpriteBundle {
        texture: asset_server.load("tiles.png"),
        transform: Transform::from_xyz(0., 40., 10.),
        ..default()
    });

    let map_size = TilemapSize { x: 6, y: 3 };

    let tilemap_entity = commands.spawn_empty().id();

    let mut tile_storage = TileStorage::empty(map_size);

    // color-corrected
    for x in 0..map_size.x {
        let tile_pos = TilePos { x, y: 0 };
        let tile_entity = commands
            .spawn(TileBundle {
                color: corrected.into(),
                texture_index: TileTextureIndex(x),
                position: tile_pos,
                tilemap_id: TilemapId(tilemap_entity),
                ..Default::default()
            })
            .id();
        tile_storage.set(&tile_pos, tile_entity);
    }
    // colored
    for x in 0..map_size.x {
        let tile_pos = TilePos { x, y: 1 };
        let tile_entity = commands
            .spawn(TileBundle {
                color: color.into(),
                texture_index: TileTextureIndex(x),
                position: tile_pos,
                tilemap_id: TilemapId(tilemap_entity),
                ..Default::default()
            })
            .id();
        tile_storage.set(&tile_pos, tile_entity);
    }
    // uncolored
    for x in 0..map_size.x {
        let tile_pos = TilePos { x, y: 2 };
        let tile_entity = commands
            .spawn(TileBundle {
                texture_index: TileTextureIndex(x),
                position: tile_pos,
                tilemap_id: TilemapId(tilemap_entity),
                ..Default::default()
            })
            .id();
        tile_storage.set(&tile_pos, tile_entity);
    }

    let grid_size = tile_size.into();
    let map_type = TilemapType::default();

    commands.entity(tilemap_entity).insert(TilemapBundle {
        grid_size,
        map_type,
        size: map_size,
        storage: tile_storage,
        texture: TilemapTexture::Single(texture_handle),
        tile_size,
        transform: get_tilemap_center_transform(&map_size, &grid_size, &map_type, 0.0),
        ..Default::default()
    });
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins.set(ImagePlugin::default_nearest()))
        .add_plugins(TilemapPlugin)
        .add_systems(Startup, startup)
        .add_systems(Update, helpers::camera::movement)
        .run();
}
```

</details>

<img width="1280" alt="Screenshot 2023-10-15 at 9 34 26 AM" src="https://github.com/StarArawn/bevy_ecs_tilemap/assets/200550/dfb1045b-c260-4a01-a236-66b964231e6f">

**Comment by inodentry** [comment]
@rparrett no, the base color is white (#FFFFFF), because i specifically designed these sprites with the intention of colorizing them. The grey color on the "neutral" tiles is also created with colorization. You can see it also looks different in the two screenshots.

Also, even if the base color was not white, the issue here is that bevy_ecs_tilemap behaves inconsistently with Bevy Sprites. So one of the two implementations must be wrong. Based on how the colors look (and I know how they *should* look, when I played around with colors in external software), this crate is wrong and bevy sprites are correct.

**Comment by rparrett** [comment]
Does #481 fix the issue for you?

**Comment by inodentry** [comment]
@rparrett Oh, yes. I'm very sorry, I forgot to respond to you. I applied the patch/PR to my game and it works nicely. :)
