### ISSUE TITLE
MapQuery's get_tile_entity crashes with an index out of bounds instead of returning MapTileError::OutOfBounds

### ISSUE THREAD

**Issue by Elabajaba** [StarArawn/bevy_ecs_tilemap#48]
When you attempt to call get_tile_entity with an index that is out of bounds, it panics instead of returning MapTileError. (eg. on a 12x12 tile map a tile_position of (17, 0) will cause it to panic. (16, 0) will also panic, but (15, 0) won't panic).

**Comment by StarArawn** [comment]
Interesting. I'll take a look at this. I think I want to move away from morton encoding as we don't really benefit much from it and instead use row major ordering instead.
