### ISSUE TITLE
License shown as "non-standard" on crates.io

### ISSUE THREAD

**Issue by poperigby** [StarArawn/bevy_ecs_tilemap#490]
On [crates.io](https://crates.io/crates/bevy_ecs_tilemap), your license is shown as "non-standard" even though you're using the MIT license. I'm not entirely sure why, but my guess is it's because you've set `license-file` in your `Cargo.toml`. I don't think that's necessary if you've already specified `license`.

**Comment by StarArawn** [comment]
This should be fixed now. We should just be using license-file not both.

**Comment by StarArawn** [comment]
v0.12.0 is out now this should be fixed.

**Comment by StarArawn** [comment]
This is not fixed. I'll look into it more..
