### ISSUE TITLE
Correct process to add a Collider

### ISSUE THREAD

**Issue by richchurcher** [StarArawn/bevy_ecs_tilemap#504]
Hello and thank you for `bevy_ecs_tilemap`! I'm playing with tilemaps and `bevy_xpbd`, and I wonder if perhaps this is just inexperience or if I'm encountering a side effect of #500, but I'm having a hard time getting tiles in a tilemap to collide with a player object (just a 2d mesh with a transform, an xpbd `RigidBody::Dynamic` and an xpbd `Collider`).

Given something like this, I notice there are invisible colliders in the middle of the tilemap square, but nothing around its edges:

```rust
fn generate_level_map(asset_server: Res<AssetServer>, mut commands: Commands) {
    let tilemap_entity = commands.spawn_empty().id();
    let map_size = TilemapSize { x: 64, y: 64 };
    let texture_handle = asset_server.load("textures/tiles.png");
    let map_type = TilemapType::Square;
    let tile_size = TilemapTileSize { x: 16., y: 16. };
    let grid_size = tile_size.into();

    // Each room can have its own tilemap, at least for now.
    let mut room_storage = TileStorage::empty(map_size);

    for x in 0..map_size.x {
        for y in 0..map_size.y {
            if x == 0 || x == map_size.x - 1 || y == 0 || y == map_size.y - 1 {
                let tile_pos = TilePos { x, y };
                let center = tile_pos.center_in_world(&grid_size, &map_type);

                let tile_entity = commands
                    .spawn((
                        RigidBody::Static,
                        Collider::cuboid(16., 16.),
                        SpatialBundle::from_transform(Transform::from_xyz(center.x, center.y, 0.)),
                        TileBundle {
                            position: tile_pos,
                            tilemap_id: TilemapId(tilemap_entity),
                            ..Default::default()
                        },
                    ))
                    .id();
                room_storage.set(&tile_pos, tile_entity);
            }
        }
    }

    let transform = get_tilemap_center_transform(&map_size, &grid_size, &map_type, 0.0);

    commands.entity(tilemap_entity).insert(TilemapBundle {
        grid_size,
        map_type,
        size: map_size,
        storage: room_storage,
        texture: TilemapTexture::Single(texture_handle),
        tile_size,
        transform,
        ..Default::default()
    });

    #[cfg(all(not(feature = "atlas"), feature = "render"))]
    {
        array_texture_loader.add(TilemapArrayTexture {
            texture: TilemapTexture::Single(asset_server.load("textures/tiles.png")),
            tile_size,
            ..Default::default()
        });
    }
}
```
(adapted from the `basic` example). I'd be happy to contribute an example once I get all this cleared up, but it's entirely possible I've just misunderstood the basics. Any pointers to examples or clarifying where I'm going wrong would be super helpful.

![image](https://github.com/StarArawn/bevy_ecs_tilemap/assets/171905/6c27cb6f-7bbf-44fd-a9f2-142442d3a202)

(screenshot shows player in green, enemy in red, tile "wall" in orange and obviously not colliding with anything).

**Comment by rparrett** [comment]
Adding a physics debug visualization will help you here. Here's how to do that in [xpbd](https://docs.rs/bevy_xpbd_2d/latest/bevy_xpbd_2d/plugins/debug/struct.PhysicsDebugPlugin.html).

Your issue seems to be that your `Tilemap` has a transform that our individual tiles aren't inheriting. You can either add
```rust
commands.entity(tilemap_entity).add_child(tile_entity);
```
to your tile spawning code, or remove the offset from the `Tilemap`.

**Comment by richchurcher** [comment]
That's immediately so much clearer! Colliders were nowhere near the tiles.

![image](https://github.com/StarArawn/bevy_ecs_tilemap/assets/171905/32ddbe33-957d-4a43-ae6f-b1d13fd66163)

Adding the tile as a child of the map works a treat (I wasn't sure how to go about removing the offset).

Would a simple example of tile collision be useful, or is it a bit much given it'd add `bevy_xpbd` as a dev dependency?

**Comment by rparrett** [comment]
> or is it a bit much given it'd add `bevy_xpbd` as a dev dependency?

I know @StarArawn has been contemplating removing the `tiled` and `ldtk` examples recently, with the goal of reducing the scope of this project a bit. So I think that a PR like that would be unlikely to get merged. It seems like a useful example to show the world, but maybe not as an example in this repository.

**Comment by richchurcher** [comment]
Exactly right. I might chuck something in a gist and link it from here, should be sufficient documentation.

**Comment by richchurcher** [comment]
This should do the trick: https://github.com/richchurcher/tile_collision_example_xpbd

Cheers!
