### ISSUE TITLE
Wrong tiles placement when images height are superior to tiles height with isometric maps

### ISSUE THREAD

**Issue by sovietsky-cyborg** [StarArawn/bevy_ecs_tilemap#511]
I try to import an isometric map from tiled, this map has tiles with size of 64 * 32, 
I use some "canyons" tiles on another layer whose size is 64*96 and it seems to render well with tiled

![Screenshot from 2024-02-03 22-40-42](https://github.com/StarArawn/bevy_ecs_tilemap/assets/5341188/952e9539-01ee-46eb-83ed-8ecf83d436af)

but when i try to render this map with `helper/titled.rs`, i get a misplacement for canyons

 
![Screenshot from 2024-02-03 22-28-04](https://github.com/StarArawn/bevy_ecs_tilemap/assets/5341188/cbe31e61-8f36-45d1-978d-9cd50448990b)

In fact, it seems that the image position is rendered relative to the center of it, not the bottom, so if the image height is bigger than the tile height, it will be misplaced, it is a normal behavior ?

Sorry for the beginner's question, i am very new to bevy

**Comment by StarArawn** [comment]
You need to modify the rendering of the tilemap to include y-sorting. Please look at the latest examples 3d iso example.

**Comment by sovietsky-cyborg** [comment]
ok, this bug has happened because i didnt set any info about the offsetx/offsety which result in this misplacement
