### ISSUE TITLE
TileStorage, TilemapSize, TileTextureIndex, TilePos are not Components anymore.

### ISSUE THREAD

**Issue by peregrine-l** [StarArawn/bevy_ecs_tilemap#513]
I noticed that this crate is now compatible with Bevy 0.12, so I increased Bevy's version number in my Cargo.toml and ran cargo check.  However, my code uses TileStorage, TilemapSize, TileTextureIndex and TilePos in many queries, and apparently, I cannot do that anymore, for they no more are  Components.  What is the rationale for this change?  Is there a workaround?

**Comment by rparrett** [comment]
There hasn't been a crate.io release of `bevy_ecs_tilemap` that supports Bevy 0.12 yet. See #488.

The error you are seeing (random things no longer being components) is often indicative of there being multiple versions of Bevy in your dependency tree. A `Bevy 0.11` `Component` is a different type than a `Bevy 0.12` component.

Unless you're specifying this git repo in your `Cargo.toml`, `bevy_ecs_tilemap` is still pulling in Bevy 0.11.

**Comment by StarArawn** [comment]
v0.12.0 is out now this should be fixed.
