### ISSUE TITLE
Hide entire layer

### ISSUE THREAD

**Issue by IceSentry** [StarArawn/bevy_ecs_tilemap#52]
I'm working on a dwarf fortress style map with multiple z-level used to represent a 3rd dimension while keeping everything 2d. 

Currently, I'm using a different layer for each z_level. When I want to change the current z_level I simply hide any layers above the current one. My problem is that, to do this I have to set every tile in each layer to be not visible. I know there's a despawn_layer (technically, depsawn_layer 😉), but when I used it I couldn't figure out how to rebuild a layer at run time and I also don't think I should do that any way. 

Essentially, what I want is a way to set an entire layer to not visible without having to loop on every tile.

Also, what's the best place to ask a question about this crate? Should I just ask in the bevy discord channel?

**Comment by StarArawn** [comment]
We should have a way of hiding entire layers. Thanks for the issue!

**Comment by StarArawn** [comment]
This is now complete please use the Visibility component on the TileMap bundle!
