### ISSUE TITLE
Instead ov `src/map/mod.rs`, it should just be `src/map.rs`.

### ISSUE THREAD

**Issue by CalinZBaenen** [StarArawn/bevy_ecs_tilemap#520]
Unless there are plans to add more to the `src/map` directory, I believe `src/map/mod.rs` should become `src/map.rs`.  
This change would, structurally, make more sense, as there is not really a reason for `mod.rs` to be all alone in its own directory.

If there is any reason why it is like this, let me know;  I am interested to hear why it is designed like this.

**Comment by StarArawn** [comment]
> Unless there are plans to add more to the `src/map` directory, I believe `src/map/mod.rs` should become `src/map.rs`. This change would, structurally, make more sense, as there is not really a reason for `mod.rs` to be all alone in its own directory.
> 
> If there is any reason why it is like this, let me know; I am interested to hear why it is designed like this.

At one point there was more in that folder. After so much change its just legacy at this point.

**Comment by CalinZBaenen** [comment]
I see...  
I believe this change should be made for cleanness' sake – unless there are plans to add content to the folder again.

As far as I am aware, making the change would not be breaking, as Rust recognizes `x.rs` and `x/mod.rs` the same.
