### ISSUE TITLE
Improve Tiled support

### ISSUE THREAD

**Issue by kim-fg** [StarArawn/bevy_ecs_tilemap#524]
Hi, fresh user of the project here.

I ran into a weird issue when I transitioned from sprite based environments to using this project with Tiled.
The fact that there isn't a tiled helper included through, even through features, is not a very smooth experience.

My suggestion is for there to be some work put into moving the helper code from examples to the crate and leave it behind a feature flag.
I did read the [helper](https://github.com/StarArawn/bevy_ecs_tilemap/blob/25def41e029626bb5e84fe7aca1f16a1d6beccdc/examples/helpers/tiled.rs) and yes, with correct logic for whether the atlas flag is used or not.

I've never worked with feature flag implementation, but I'm happy to learn and help where I can.

**Comment by kim-fg** [comment]
After a bit of thinking I think it would be valid to split up the example in two instead of using the atlas flag for it at all. There is like the comment says no way to make it work from a direct copy which feels unintuitive.  

Is there a reason this wasn't done from the beginning?

**Comment by StarArawn** [comment]
I don't want to add more tiled support to this crate. I would rather have a `bevy_tiled` which handles loading in tiled maps. This is how `bevy_ecs_ldtk` and I think that has worked well.

**Comment by kim-fg** [comment]
Fair enough, I'll close the issue.
