### ISSUE TITLE
Manage z-index with spritesheet moving character

### ISSUE THREAD

**Issue by sovietsky-cyborg** [StarArawn/bevy_ecs_tilemap#533]
i try to use an animated character in my project but i'm not sure how to integrate it correctly with an isometric tilemap,

The map is rendered from a .tmx file loaded with the  tiled.rs helper, then, i use SpriteSheetBundle to render my character sprite but the main problem occur with the z coordinate from the environment:

![Screenshot from 2024-05-24 15-32-41](https://github.com/StarArawn/bevy_ecs_tilemap/assets/5341188/6c5368fa-78b6-437d-98ba-4bdf622b5f93)

In this case, even if i increase the z coordinate of my sprite to 100, it will be rendered behind the tree

![Screenshot from 2024-05-24 15-04-00](https://github.com/StarArawn/bevy_ecs_tilemap/assets/5341188/b5abbd6a-8d8a-457d-907b-3a4613763055)

I also notice that after a certain threshold, my sprite go behind the whole tilemap,
i think it is related to y-sorting, the z coordinate is increased as we descend into the y axis to allow correct rendering

So, i had 2 possible solutions for that:

-  keep track of the z coordinate for each neighboring tile and use it to update the transform of my sprite character accordingly, but as said above this not seems to change anything

- or alternatively, to integrate my character directly into the tilemap, but in this case, how do i manage his movement animation  ?

Could you tell me if you have some insights about a better solution ?

**Comment by sizeak** [comment]
Hi @sovietsky-cyborg, I'm having a similar problem. Did you find a better solution in the end? Thanks!
