### ISSUE TITLE
TilemapPlugin trait bound not satistfied for bevy 0.14.0

### ISSUE THREAD

**Issue by ASoldo** [StarArawn/bevy_ecs_tilemap#538]
There is an issue when I try to use `bevy_ecs_tilemap` in new bevy project.

https://github.com/StarArawn/bevy_ecs_tilemap/blob/aee4779c50f22dceaef946218260caf34011a757/examples/accessing_tiles.rs#L163

**Comment by rparrett** [comment]
See https://github.com/StarArawn/bevy_ecs_tilemap/issues/516

**Comment by ChristopherBiscardi** [comment]
0.14 is [published now](https://docs.rs/bevy_ecs_tilemap/0.14.0/bevy_ecs_tilemap/)
