### ISSUE TITLE
Consider adding another maintainer and cargo owner

### ISSUE THREAD

**Issue by rparrett** [StarArawn/bevy_ecs_tilemap#541]
With `bzm3r` no longer involved in the Bevy space and @StarArawn being quite busy, we could use another Maintainer.

I think I'm the only other user with permissions on this repo, and things are set up in such a way that I can press the merge button only with a GH approval from a user with write access.

This is making it very difficult to get work merged, or to be motivated to help get work into a mergable state.

Additionally, we haven't had an official Cargo release targeting Bevy 0.13 or Bevy 0.14, which is making it difficult to maintain crates like `bevy_ecs_ldtk` which depend on `bevy_ecs_tilemap`.

I am proposing that @ChristopherBiscardi be added as a maintainer and cargo-owner of the crate, and if possible, to formalize some sort of process for getting PRs reviewed and merged.

**Comment by StarArawn** [comment]
I'm okay with this. Ultimately though the goal for this repo is for it to be merged directly into bevy. I've done a little bit of work to facilitate this but its not super clear how to start the process.

**Comment by ChristopherBiscardi** [comment]
I'm comfortable with taking on maintenance and between @rparrett and myself we can probably figure out what the path to upstreaming looks like. My guess is it turns into a working group of some kind, if upstream is amenable.

**Comment by ChristopherBiscardi** [comment]
I've been added and have merged code, so going to close this.

**Comment by rparrett** [comment]
Thanks @StarArawn !
