### ISSUE TITLE
Use two generics in MapQuery API

### ISSUE THREAD

**Issue by alice-i-cecile** [StarArawn/bevy_ecs_tilemap#55]
Many methods on [MapQuery](https://docs.rs/bevy_ecs_tilemap/0.4.0/bevy_ecs_tilemap/struct.MapQuery.html#method.get_tile_entity) expose a generic, which must impl `Into<u16>`.

This is a great pattern, to allow people to use smarter, clearer types rather than passing around magical u16 values for the map and layer. However, the standard use of this (or at least, how I want to use it!) is to implement two enums (or other data types): one for the map, and one for the layer. However the generic type used must be the same in both instances, causing this pattern to create a compile error.

Swapping to two seperate generic types with the same bounds will resolve this problem.

**Comment by StarArawn** [comment]
Thankfully this is already fixed in main and has been for quite some time! You can see an example here:
https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/src/map_query.rs#L144

**Comment by alice-i-cecile** [comment]
Aha, that's much better. Great!
