### ISSUE TITLE
Tiles should render with anchor ButtonLeft.

### ISSUE THREAD

**Issue by darkautism** [StarArawn/bevy_ecs_tilemap#567]
In Tiled editor
![image](https://github.com/user-attachments/assets/7866c075-3432-4216-91a9-b52ac068a9d5)
![image](https://github.com/user-attachments/assets/0fda3be3-8114-474e-b99e-3dbc661ad2d7)

In Game:
![image](https://github.com/user-attachments/assets/21d2b9b7-a1e2-46d3-892f-b8a7bd5282d9)

**Comment by ChristopherBiscardi** [comment]
I'm not sure what this images in this issue are supposed to be showing, but the Tiled example is a demo and not meant to be full featured. If you believe this is an issue in bevy_ecs_tilemap and not the Tiled integration you're using then please update the issue with some more explanation and a reproduction case.
