### ISSUE TITLE
Consider adding `drain` method to `TileStorage`

### ISSUE THREAD

**Issue by rparrett** [StarArawn/bevy_ecs_tilemap#579]
I'd like to be able to easily despawn all the tiles in a tilemap without putting them in a Bevy hierarchy.

Also, it would be nice if `remove` returned the removed entity, if there was one.

**Comment by ChristopherBiscardi** [comment]
feels like drain makes sense. Have to set all drained items to None and probably only return the Entitys. So probably a bunch of removes with the change would do it simply enough.

we can easily return the entity from remove. it's already a [take](https://github.com/StarArawn/bevy_ecs_tilemap/blob/73124f42dd9d43c78f3fb2a1d2d4b6f013d8e3bc/src/tiles/storage.rs#L93), so we just remove the semicolon and add the return value.
