### ISSUE TITLE
Layout of hex tiles is inaccurate, with error accumulating

### ISSUE THREAD

**Issue by alice-i-cecile** [StarArawn/bevy_ecs_tilemap#58]
While working on a tile-coordinates-from-mouse-click utility, @plof27 and I noticed that coordinates of the hex tiles become progressively more inaccurate the farther from the origin you get. You can see the [utility function](https://github.com/Leafwing-Studios/bevy-tower-defense-template/blob/main/src/utils.rs#L39) we used for conversions at the link.

We noticed this using a point-up, `Hextype::Row` layout. It works perfectly for x, but gets progressively worse on the y-axis as you get further from the origin. I suspect this is a layout bug as a result; particularly as it was still an issue using an alternate pixel-based renderer.

**Comment by StarArawn** [comment]
What map size does it start to become inaccurate at? Do you have a screenshot I can see of the inaccuracies?

**Comment by alice-i-cecile** [comment]
I'll see if I can grab some more diagnostics for you soon. If you need it sooner, the full repo linked there is open source and you can poke around.

**Comment by bzm3r** [comment]
Fixed by #268
