### ISSUE TITLE
Question: How can you migrate a tile to a new chunk

### ISSUE THREAD

**Issue by loogie** [StarArawn/bevy_ecs_tilemap#61]
I have created a small test with a bg layer of tiles, and a second sparse layer on top with a player tile that moves with the keys. Upon moving from one chunk to another the player tile stops moving until the position returns to the original chunk.

I'm just updating the UVec2 position, and using notify_chunk_for_tile() from mapquery. Should I be going about this in a different way?

**Comment by StarArawn** [comment]
I would strongly suggest decoupling your player rendering from the tile map and instead render dynamic entities using bevy's sprite system. Is that not an option due to performance concerns?

**Comment by loogie** [comment]
its definitely doable. I am attempting a roguelike game that is tilebased so i figured i could use a sparse layer. I did get it to work by despawning/adding the tile, but long term i'll probably do what is suggested. Are the tilemap layers placed in z order? as in can I add a tilemap on top of a sprite by specifying the z position?

**Comment by StarArawn** [comment]
I think it's a good idea to support "moving" tiles in the future. I just haven't figured out a good way of handling that yet. 

Also in response to your second question. Tile map layers are position using z values starting at 0 and incrementing by 1 for each layer. This means that layer_id and its corresponding z-index are the same.

**Comment by loogie** [comment]
The layer_id is great. I would like the option to at least place the player between layers in need be (building roof, foliage, etc)

and thanks for building this, it works pretty much how I would expect it to work, unlike some of the other options out there.
