### ISSUE TITLE
Error setting features in cargo.toml

### ISSUE THREAD

**Issue by jsmtux** [StarArawn/bevy_ecs_tilemap#62]
I am trying to make use of this library to load a ldtk map.
I added the following line to the cargo.toml:
`bevy_ecs_tilemap = { version = "0.4.0", features = ["ldtk"] }`
and I am getting the following error:
`the package `bevy-multi` depends on `bevy_ecs_tilemap`, with features: `ldtk` but `bevy_ecs_tilemap` does not have these features.`
Also, docs.rs it does not show any feature flags.
Is there any reason why the tiled and ldtk are not published, or am I doing something wrong?

**Comment by mlflabs** [comment]
I was about to write a question about this here too, 1 min too late :)

**Comment by StarArawn** [comment]
There isn't a specific reason that LDTK and Tiled features aren't released yet other than a lack of time on my part to finish up the ISO branch I have.

In the meantime you can target main using:
`bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap", brach = "main" }`

**Comment by jsmtux** [comment]
Thank you very much for the quick answer!
