### ISSUE TITLE
Pathfinding

### ISSUE THREAD

**Issue by mlflabs** [StarArawn/bevy_ecs_tilemap#63]
Sorry if this is a noob question.

I was just researching about the best way to traverse the tiles using aStar algorithm. In the past I just kept the grid data in an array or hashmap, but now with the entity system, whats the best resource non intensive way to do this?

**Comment by StarArawn** [comment]
The tile entities are already in an array. You'll want to look at:

`get_tile_entity`
https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/src/map_query.rs#L144
`get_tile_neighbors`
https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/src/map_query.rs#L144

You can also see an implementation of astar here:
https://github.com/StarArawn/bevy_roguelike_prototype/blob/main/src/game/map/generate_map.rs#L87

**Comment by mlflabs** [comment]
Thx for the links this helps a lot

i dont want to start a new thread, but have another question, not sure if its with tilemap or bevy, but how would i setup a query where i loop through all the tiles in a particular chunk?

**Comment by StarArawn** [comment]
> Thx for the links this helps a lot
> 
> i dont want to start a new thread, but have another question, not sure if its with tilemap or bevy, but how would i setup a query where i loop through all the tiles in a particular chunk?

Chunks are mainly meant to be a rendering optimization technique only, but if you really need to you can access the chunks via the map entity. You can't or rather wont be able to use map_query in this instance as it doesn't expose chunks. You can look at the logic for grabbing a chunk though and use something similar in your own code.

Once you have a chunk you can use:
https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/src/chunk.rs#L183

**Comment by mlflabs** [comment]
Thank you for all the replies

now my goal is just to divide the load into several frames, dont iterate through all tiles, i thought that each frame just iterate through a single chunk tiles would be nice, but is this the bevy way, is there a better way to do this?

**Comment by StarArawn** [comment]
> Thank you for all the replies
> 
> now my goal is just to divide the load into several frames, don't iterate through all tiles, i thought that each frame just iterate through a single chunk tiles would be nice, but is this the bevy way, is there a better way to do this?

I wouldn't necessarily say its the bevy way, as bevy is quite flexible, but I can understand the need to do this. It might be a better idea to keep track of tile entities(I would use tile position) yourself using some sort of hierarchical storage. HPA* comes to mind.
https://docs.rs/hierarchical_pathfinding/0.4.3/hierarchical_pathfinding/

**Comment by mlflabs** [comment]
thank you again for the reply, help a lot
