### ISSUE TITLE
MapTileError doesn't impl Error

### ISSUE THREAD

**Issue by IceSentry** [StarArawn/bevy_ecs_tilemap#65]
I tried using ? to return from a function that returns an anyhow::Result<()> but it couldn't convert the Result because Error is not implemented.

**Comment by SteveXCIV** [comment]
👋 Hi, I went to PR a fix for this issue, but it looks like it's already been done as of [02da22aa](https://github.com/StarArawn/bevy_ecs_tilemap/blame/02da22aacafb5c1be636135087c9661d3ac26927/src/error.rs#L14).

cc @StarArawn I think this can be closed?

**Comment by IceSentry** [comment]
Yeah, that seems good to me. I haven't used it in a while so didn't notice it was fixed.
