### ISSUE TITLE
Is there a way to use TextureAtlas?

### ISSUE THREAD

**Issue by ricardoalcantara** [StarArawn/bevy_ecs_tilemap#72]
I am trying to use this lib but I could not find a way to set my TextureAtlasHandler with my textures in it. Is it possible?
[edit]
I found that the Tile has a property for texture_index  but could not find any property to set the atlas.
```rust
/// The texture index in the atlas or array.
    pub texture_index: u16,
```

**Comment by PatrickLerner** [comment]
Did you notice the `examples` directory here in the repo? It has a lot of illustrative examples for usage :)

e.g. https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/examples/map.rs

**Comment by ricardoalcantara** [comment]
@PatrickLerner yes I did! I have checked it many times, I tried very hard to make it works with TextureAtlas, you cannot even find the word 'atlas' in this example. Did you understand my question?

**Comment by StarArawn** [comment]
I opted against using the texture atlas because I want to eventually use texture arrays, however it is possible to do something like:
```rust
let mut texture_atlas_builder = TextureAtlasBuilder::default();
for handle in rpg_sprite_handles.handles.iter() {
      let texture = textures.get(handle).unwrap();
      texture_atlas_builder.add_texture(handle.clone_weak().typed::<Texture>(), texture);
}

let texture_atlas = texture_atlas_builder.finish(&mut textures).unwrap();
let texture_atlas_texture = texture_atlas.texture.clone();
atlas_handle = texture_atlases.add(texture_atlas);
let material_handle = materials.add(ColorMaterial::texture(texture_atlas_texture));

...

let layer_entity = map_query.build_layer(&mut commands, layer_builder, material_handle);
```

I haven't tested the code above so it might need some tweaking..

**Comment by ricardoalcantara** [comment]
@StarArawn Hi, thanks for your answer! I still think this is quit complex and I am not very experienced with bevy and rust, I still can't use it because I have a SpriteSheet with all my tiles, I think SpriteSheet with all tiles is a common usage for tilemaps, 
it would be useful to have an example with that Texture Array using a spritesheet.

I like the ideal of having all my tiles as entities so I could later implement more feature on specific tiles, different from bevy_tilemap which the tilemap is the entity and I need to for loop for all tiles or index it somehow, but with bevy_tilemap I can easily load my atlas, use the add_texture to specify the indexes (areas of sprite) and later set the texture_index to my tile desired texture.

**Comment by StarArawn** [comment]
Bevy has a function called `from_grid` on the `TextureAtlas` struct.

https://github.com/bevyengine/bevy/blob/10b0b1ad407f31817c401a02e5e08358b615992c/crates/bevy_sprite/src/texture_atlas.rs#L104

**Comment by ricardoalcantara** [comment]
The problem isn't creating the TextureAtlas, it's that I cannot pass it to ColorMaterial::texture(), I tried and it breaked.

**Comment by ricardoalcantara** [comment]
From Discord:
StarToaster — 07/26/2021 at 10:18 AM
@ricardoalcantara Ah I see, that isn't possible currently in bevy_ecs_tilemap. Bevy keeps track of each individual rectangle and passes all of them to the shader. I think a grid approach works better and is simpler, but I can understand that's not always the most convenient way of handling it. The reason why I opted to go with my own atlas like solution is to eventually be able to support texture arrays, but they haven't been added in yet. I think a better solution here would be to edit your spritesheet by separating out map tiles. They already appear to be in a grid of some sort.
