### ISSUE TITLE
Missing chunks

### ISSUE THREAD

**Issue by B-Reif** [StarArawn/bevy_ecs_tilemap#74]
After creating a tilemap, I only see one chunk rendering when I am expecting four chunks.

```rs
fn setup_tilemap(
    // -- snip --
) {
    // 2 chunks wide, 2 chunks tall. Expecting 4 chunks total.
    let map_size = UVec2::new(2, 2);

    // Each chunk is 16 tiles wide and 9 tiles tall.
    let chunk_size = UVec2::new(16, 9);

    let layer_settings = LayerSettings::new(
        map_size,
        chunk_size,
        Vec2::new(16., 16.),
        Vec2::new(192.0, 16.0),
    );
    // -- snip --
}
```
Ingame this only renders one 16x9 chunk:
![image](https://user-images.githubusercontent.com/12357846/127907212-143a569b-8e17-4e25-8805-28a0baf504ea.png)

Here is a [gist](https://gist.github.com/B-Reif/20f9e2e0e5256ec3707b47cf258817b0) with the complete tilemap setup function.

Let me know what other information I can provide.

**Comment by B-Reif** [comment]
full repro app
https://github.com/B-Reif/tile_repro

**Comment by anhyzer2602** [comment]
In your tile_repro app, remove line 21 and change line 38 from ```.entity(entity)``` to ```.entity(map_entity)```.

I haven't traced exactly how the internals work, but it looks like you need to insert your map component onto the same entity that is passed into the Map::new() function.

**Comment by B-Reif** [comment]
Great catch, this fixes it. I'll close this issue for now.

It might be worth either refactoring this API to prevent this, or providing a specific warning when this happens. The behavior resulting from this mistake was very confusing to me.
