### ISSUE TITLE
Not able to import isometric maps correctly.

### ISSUE THREAD

**Issue by edgarssilva** [StarArawn/bevy_ecs_tilemap#75]
I've tried to importing a tmx from Tiled where the map his 16x8 but with a tileset of 16x16 to give it a isometric look.
The problem is that bevy is rendering the tiles with 16px of height between them, maybe because the of tile dimensions idk :P.

Really like the project btw.

**Comment by StarArawn** [comment]
Check out the iso PR it has a lot of iso changes that make things work a lot better.

https://github.com/StarArawn/bevy_ecs_tilemap/pull/45

**Comment by edgarssilva** [comment]
I've specified the branch in the Cargo.toml and it fixed the problem without any changes.
Keep up the great work!
