### ISSUE TITLE
Unable to use ldtk 

### ISSUE THREAD

**Issue by edil3ra** [StarArawn/bevy_ecs_tilemap#82]
the package `bevy_play` depends on `bevy_ecs_tilemap`, with features: `ldtk` but `bevy_ecs_tilemap` does not have these features.

```
[package]
name = "bevy_play"
version = "0.1.0"
edition = "2018"


[dependencies]
bevy = { version = "0.5"}
bevy_ecs_tilemap = {version = "0.4.0", features = ["ldtk"]}

```

**Comment by StarArawn** [comment]
`ldtk` doesn't exist in any current versions of the library. Instead you can use:

`bevy_ecs_tilemap = { git="https://github.com/StarArawn/bevy_ecs_tilemap", rev="c221c80356e25df88d49aa42f6627cfb0d520dbe", features= ["ldtk"] }`
