### ISSUE TITLE
Add borders to default assets

### ISSUE THREAD

**Issue by alice-i-cecile** [StarArawn/bevy_ecs_tilemap#86]
This will make it easier for users to clearly understand the effects of changes to their code when experimenting with the examples.

**Comment by alice-i-cecile** [comment]
Here's a completed version of `tiles.png` that works for me locally. Feel free to use it.

![tiles](https://user-images.githubusercontent.com/3579909/130544327-05458439-78ee-40ea-8cd4-700e37eac7ee.png)

**Comment by StarArawn** [comment]
Can you open a PR for this? Thanks! 👍

**Comment by alice-i-cecile** [comment]
Can do. Do we want to make the same changes to the other tiles too? Looks like `iso_color` and `flat_hex_tiles` have the same issue. I'll probably just regenerate them from scratch rather than trying to modify the images.
