### ISSUE TITLE
ldtk tilemap src vs t field

### ISSUE THREAD

**Issue by ChristopherBiscardi** [StarArawn/bevy_ecs_tilemap#91]
The ldtk tilemap [texture index code](https://github.com/StarArawn/bevy_ecs_tilemap/blob/93969ae426fdaa32be70625e6f725ad1cd7eddb1/src/ldtk.rs#L174-L187) uses the `src` field to calculate the tilemap index based on the pixel dimensions. There seems to be a bug in the current implementation that offsets the index by 1 for the first row, and 2 for every row after that in the tilemap.

Here's an image showing the current behavior:

![Screen Shot 2021-08-24 at 1 00 22 PM](https://user-images.githubusercontent.com/551247/130685894-f2d65be2-59c1-41e8-a02f-8dbefa19204d.png)

There seems to be an index for the tilemap in the `t` field in the same struct. Changing the above code to access the `t` field instead results in the following, seemingly correct output for the tilemap.

```rust
layer_builder.set_tile(
    pos,
    Tile {
        texture_index: tile.t as u16,
        ..Default::default()
    }.into()
).unwrap();
```

![image](https://user-images.githubusercontent.com/551247/130685988-90b6542c-328a-4734-bf3d-2c09ab58ea85.png)

I don't know enough about tdlk to know if this is correct, but it seemed useful to file an issue for

**Comment by StarArawn** [comment]
I believe this is no longer an issue, but please reopen if that's not the case.
