### ISSUE TITLE
TilePos and relatives should use usize, not u32

### ISSUE THREAD

**Issue by alice-i-cecile** [StarArawn/bevy_ecs_tilemap#95]
This is an important perf and usability optimization when interfacing with external arrays (which are always indexed by `usize` slices).

Currently, you must repeatedly waste operations performing this conversion and littering the code base with `as usize`.

**Comment by inodentry** [comment]
FYI there is no perf cost; integer type conversions compile to no-ops, there are no extra operations. There is no such thing as integer type conversion at the assembly / machine code level.

This is just to make Rust code prettier and more correct.

**Comment by StarArawn** [comment]
I think this is no longer relevant, but feel free to reopen if I am wrong.
