### ISSUE TITLE
Load entities from ldtk

### ISSUE THREAD

**Issue by Aposhian** [StarArawn/bevy_ecs_tilemap#98]
Currently I am implementing custom logic to load entities from ldtk. I am going to try adding this generically in my fork.

**Comment by Aposhian** [comment]
My [current code](https://github.com/Aposhian/bevy-sandbox/blob/c92e4438f7f92ecf5ac9effb3c612a37a7b7e8a7/examples/ldtk_entities.rs#L58) works by implementing `From<EntityInstance>` for a custom type, and then sending the relevant information for spawning as an event to a spawning system.

My initial idea for making this more ergonomic in this library was directly sending `EntityInstance` as events for user code to integrate into game engine logic. However, the only way I can think to get that to work is to clone the entire `EntityInstance` object before cloning.

Another idea is to make the `LdtkPlugin` generic to entity type definitions, and then send events for each of those individually, but that would require reflection and may become really messy.

Thoughts?

**Comment by StarArawn** [comment]
Please see:
https://github.com/StarArawn/bevy_ecs_tilemap/issues/84
